#===============================================================================
#
# ELF Lib
#
# GENERAL DESCRIPTION
#    build script
#
# Copyright (c) 2018 by QUALCOMM, Incorporated.
# All Rights Reserved.
# QUALCOMM Proprietary/GTDR
#
#-------------------------------------------------------------------------------
#
#  $Header: //components/rel/ssg.tz/1.1.3/securemsm/trustzone/qsapps/libs/elflib/SConscript#1 $
#  $DateTime: 2019/05/23 05:32:51 $
#  $Author: pwbldsvc $
#  $Change: 19292046 $
#                      EDIT HISTORY FOR FILE
#
#  This section contains schedulerents describing changes made to the module.
#  Notice that changes are listed in reverse chronological order.
# when      who      what
#-------------------------------------------------------------------------------
#
##===============================================================================
Import('env')
env = env.Clone()

libname = 'elf_lib'
SRCPATH = "${BUILD_ROOT}/ssg/securemsm/trustzone/qsee/mink/elflib"

includes = [
    "${BUILD_ROOT}/core/api/services",
    "${BUILD_ROOT}/core/api/kernel/libstd/stringl",
    "${BUILD_ROOT}/ssg/api/securemsm/trustzone/qsee",
    "${BUILD_ROOT}/ssg/api/securemsm/util",
    "${BUILD_ROOT}/ssg/securemsm/trustzone/qsee/include",
    "${BUILD_ROOT}/ssg/securemsm/trustzone/qsee/mink/core/inc",
    '${BUILD_ROOT}/ssg/securemsm/trustzone/qsee/mink/elflib/inc',
    "${BUILD_ROOT}/ssg/securemsm/trustzone/qsee/mink/include",
]

sources = [
    SRCPATH + "/src/elffile.c",
]

lib = env.SecureAppLibBuilder(includes, sources, libname,
    deploy_sources = ['SConscript'],
    deploy_variants = env.GetDefaultPublicVariants(),
    deploy_lib = True)

Return('lib')
