/*==============================================================================

  High Speed USB Composition Utilities 
  
  GENERAL DESCRIPTION
    This module includes various utility functions, dealing with device 
    compositions. 
      
  EXTERNALIZED FUNCTIONS
    hsu_conf_sel_comp_utils_comp_id_is_valid_for_hsu
    hsu_conf_sel_comp_utils_get_comp_details
    hsu_conf_sel_comp_utils_get_comp_details_by_hsu_id
    hsu_conf_sel_comp_utils_get_cur_prod_id
    hsu_conf_sel_comp_utils_get_default_comp_info
    hsu_conf_sel_comp_utils_get_comp_details_by_pid
    hsu_conf_sel_comp_utils_get_default_std_comp_info
    hsu_conf_sel_comp_utils_set_comp_info
  
  INITALIZATION AND SEQUENCING REQUIREMENTS
    None.

  Copyright (c) 2006 by Qualcomm Technologies, Incorporated.  All Rights Reserved.
==============================================================================*/

/*==============================================================================

                            EDIT HISTORY FOR MODULE
  
  This section contains comments describing changes made to the module.
  Notice that changes are listed in reverse chronological order.
  $Header: //components/rel/core.tx/6.0/wiredconnectivity/hsusb/driver/src/common/hsu_conf_sel_comp_utils.c#1 $
  $DateTime: 2020/01/30 22:49:35 $ $Author: pwbldsvc $
    
  when      who     what, where, why
  --------  ---     ------------------------------------------------------------
  06/29/07  bt      Added MTP (IUSBDriver) support
  09/12/06  ke      Initial version
    
==============================================================================*/

/*==============================================================================

                            INCLUDE FILES FOR MODULE
  
==============================================================================*/
#include "hsu_conf_sel_comp_utils.h"
#include "hsu_conf_sel_types_int.h"
#include "jtypes_int.h"
#include "jos_int.h"
#include "jslave_init.h"
#include "hsu_conf_sel_i.h"
#include "hsu_conf_sel_nv.h"
#include "hsu_common_int.h"
#include "hsu_log.h"

#ifdef FEATURE_GOBI
#include "hsu_conf_sel_gobi_comp.h"
#endif /* FEATURE_GOBI */

/*==============================================================================

                          DEFINITIONS AND DECLARATIONS FOR MODULE
  
==============================================================================*/

/*==============================================================================
Constants and Macros
==============================================================================*/
/*==============================================================================
  Typedefs
==============================================================================*/
/*==============================================================================
  Variables
==============================================================================*/
static hsu_conf_sel_comp_info_type const
  compositions_details[HSU_CONF_SEL_NUM_OF_COMPS] = 
{
#ifdef FEATURE_HS_USB_MS_FD
  { /* DIAG & NMEA & MS & MDM & Net device */
    HSU_CONF_SEL_DIAG_NMEA_MS_MDM_NET_COMP,
    EFS_HSU_DIAG_NMEA_MS_MDM_NET,
    HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_MS_MDM_NET,
    HSU_PROPRIETARY_CMP_ONLY,
    {1,2,1,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, NMEA_HSU_IFACE, MS_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE},
    5,
    {RDM_USB_MMC_DEV, RDM_USB_DIAG_DEV, RDM_USB_NMEA_DEV, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },
#endif /* FEATURE_HS_USB_MS_FD */
  { /* DIAG & NMEA & MDM & Net device */
    HSU_CONF_SEL_DIAG_NMEA_MDM_NET_COMP,
    EFS_HSU_DIAG_NMEA_MDM_NET,
    HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_MDM_NET,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,2,1,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, NMEA_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE},
    4,
    {RDM_USB_DIAG_DEV, RDM_USB_NMEA_DEV, RDM_USB_MDM_DEV, 
     RDM_USB_NET_WWAN_DEV, RDM_SRVC_NOT_ALLOWED},
    HSU_ECM_COMP_IS_VALID
  },
  { /* DIAG & NMEA & MDM device */
    HSU_CONF_SEL_DIAG_NMEA_MDM_COMP,
    EFS_HSU_DIAG_NMEA_MDM,
    HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_MDM,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,2,1,0,0,0,0,0,0},
    {DIAG_HSU_IFACE, NMEA_HSU_IFACE, MDM_HSU_IFACE},
    3,
    {RDM_USB_DIAG_DEV, RDM_USB_NMEA_DEV, RDM_USB_MDM_DEV, 
     RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED},
    TRUE
  },
#ifdef FEATURE_HS_USB_SER3_PORT
    { /* DIAG & NMEA & MDM & Net & SER3 device */
      HSU_CONF_SEL_DIAG_NMEA_MDM_NET_SER3_COMP,
      EFS_HSU_DIAG_NMEA_SER3_MDM_NET,
#ifdef FEATURE_GOBI
      HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_MDM_NET_SER3,
#else /* !FEATURE_GOBI */
      HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_SER3_MDM_NET,
#endif /* FEATURE_GOBI */
      HSU_PROPRIETARY_CMP_ONLY,
      {0,3,1,1,0,0,0,0,0},
      {DIAG_HSU_IFACE, NMEA_HSU_IFACE, SER3_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE},
      4,
      {RDM_USB_DIAG_DEV, RDM_USB_NMEA_DEV, RDM_USB_MDM_DEV, 
      RDM_USB_NET_WWAN_DEV, RDM_SRVC_NOT_ALLOWED},
      HSU_ECM_COMP_IS_VALID
    },
#endif
#ifdef FEATURE_HS_USB_MS_FD
  { /* MS only device */
    HSU_CONF_SEL_MS_COMP,
    EFS_HSU_MS,
    HSU_PRODUCT_ID_MS,
    HSU_SUPP_ALL_OSES_CMP,
    {1,0,0,0,0,0,0,0,0},
    {MS_HSU_IFACE},
    1,
    {RDM_USB_MMC_DEV, RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, 
     RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED},
    TRUE
  },
#endif /* FEATURE_HS_USB_MS_FD */
  { /* PictBridge device */
    HSU_CONF_SEL_PICTBRIDGE_COMP,
    EFS_HSU_NO_DEVICE, /* this composition cannot be chosen through EFS */
    HSU_PRODUCT_ID_PICTBRIDGE,
    HSU_SUPP_ALL_OSES_CMP,
    {0,0,0,0,1,0,0,0,0},
    {NO_HSU_IFACE},
    0,
    {RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, 
     RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED},
    FALSE
  },
  { /* DIAG & MDM  device */
    HSU_CONF_SEL_DIAG_MDM_COMP,
    EFS_HSU_DIAG_MDM,
    HSU_PROD_ID_SINGLE_IF_DIAG_MDM,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,1,1,0,0,0,0,0,0},
    {DIAG_HSU_IFACE, MDM_HSU_IFACE},
    2,
    {RDM_USB_DIAG_DEV, RDM_USB_MDM_DEV, RDM_SRVC_NOT_ALLOWED,
     RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED},
    TRUE
  },
  { /* DIAG & MDM & Net device */
    HSU_CONF_SEL_DIAG_MDM_NET_COMP,
    EFS_HSU_DIAG_MDM_NET,
    HSU_PROD_ID_SINGLE_IF_DIAG_MDM_NET,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,1,1,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE},
    3,
    {RDM_USB_DIAG_DEV, RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV, 
     RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED},
    HSU_ECM_COMP_IS_VALID
  },
  { /* DIAG & NMEA & MDM1 & MDM2 & Net device */
    HSU_CONF_SEL_DIAG_NMEA_MDM1_MDM2_NET_COMP,
    EFS_HSU_DIAG_NMEA_MDM1_MDM2_NET,
    HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_MDM1_MDM2_NET,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,2,2,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, NMEA_HSU_IFACE, MDM_HSU_IFACE, MDM2_HSU_IFACE, NET1_HSU_IFACE},
    5,
    {RDM_USB_DIAG_DEV, RDM_USB_NMEA_DEV,RDM_USB_MDM_DEV, RDM_USB_MDM2_DEV,RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },
  { /* DIAG MDM1 & MDM2 & Net device */
    HSU_CONF_SEL_DIAG_MDM1_MDM2_NET_COMP,
    EFS_HSU_DIAG_MDM1_MDM2_NET,
    HSU_PROD_ID_SINGLE_IF_DIAG_MDM1_MDM2_NET,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,1,2,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, MDM_HSU_IFACE, MDM2_HSU_IFACE, NET1_HSU_IFACE},
    4,
    {RDM_USB_DIAG_DEV, RDM_USB_MDM_DEV, RDM_USB_MDM2_DEV,RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  }
#ifdef FEATURE_HSU_MTP
  ,
  { /* BREW Extended dev (for using Blaster tool with BREW USBDriverDiag app) */
    HSU_CONF_SEL_BREW_EXT_COMP,
    EFS_HSU_NO_DEVICE,  /* this composition cannot be chosen through EFS */
    HSU_PRODUCT_ID_BREW_EXT,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,0,0,0,0,1,0,0,0},
    {NO_HSU_IFACE},
    0,
    {RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, 
     RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED},
    FALSE
  },
  { /* MTP dev only  */
    HSU_CONF_SEL_MTP_COMP,
    EFS_HSU_MTP,
    HSU_PRODUCT_ID_MTP,
    HSU_SUPP_ALL_OSES_CMP,
    {0,0,0,0,0,1,0,0,0},
    {NO_HSU_IFACE},
    0,
    {RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, 
     RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED},
    FALSE
  }
#endif /* FEATURE_HSU_MTP */
#ifdef FEATURE_HS_USB_MS_FD
  ,
  { /* Diag and Mass Storage */
    HSU_CONF_SEL_DIAG_MS_COMP,
    EFS_HSU_DIAG_MS,	
    HSU_PROD_ID_SINGLE_IF_DIAG_MS,
    HSU_PROPRIETARY_CMP_ONLY,
    {1,1,0,0,0,0,0,0,0},
    {DIAG_HSU_IFACE, MS_HSU_IFACE}
    2,
    {RDM_USB_MMC_DEV, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
     RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED},
    TRUE
  }
#endif /* FEATURE_HS_USB_MS_FD */
#ifdef FEATURE_HS_USB_SAMPLE_LOOPBACK
  ,
  { /* Loop  */
    HSU_CONF_SEL_LOOPBACK_COMP,
    EFS_HSU_LOOPBACK,  /* this composition can be chosen through EFS */
    HSU_PRODUCT_ID_LOOPBACK,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,0,0,0,0,0,0,1,0},
    {NO_HSU_IFACE},
    0,
    {RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, 
     RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED},
    FALSE
  }
#endif /* FEATURE_HS_USB_SAMPLE_LOOPBACK */
#if (defined FEATURE_HS_USB_MS_FD) && \
    (defined FEATURE_HS_USB_DIGITAL_AUDIO_DEVICE)
  ,
  { /* DIAG & NMEA & MS & MDM & Net $ Digital Audio device */
    HSU_CONF_SEL_DIAG_NMEA_MS_MDM_NET_AUDIO_COMP,
    EFS_HSU_DIAG_NMEA_MS_MDM_NET_AUDIO, 
    HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_MS_MDM_NET_AUDIO,
    HSU_PROPRIETARY_CMP_ONLY,
    {1,2,1,1,0,0,0,0,1},
    {DIAG_HSU_IFACE, NMEA_HSU_IFACE, MS_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE,
      AUDIO_HSU_IFACE},
    5,
    {RDM_USB_MMC_DEV, RDM_USB_DIAG_DEV, RDM_USB_NMEA_DEV, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  }
#endif /* FEATURE_HS_USB_MS_FD && FEATURE_HS_USB_DIGITAL_AUDIO_DEVICE */
#ifdef FEATURE_HS_USB_DIGITAL_AUDIO_DEVICE
  ,
  { /* Diag and Digital Audio */
    HSU_CONF_SEL_DIAG_AUDIO_COMP,
    EFS_HSU_DIAG_AUDIO,	
    HSU_PROD_ID_SINGLE_IF_DIAG_AUDIO,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,1,0,0,0,0,0,0,1},
    {DIAG_HSU_IFACE, AUDIO_HSU_IFACE},  
    1,
    {RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, 
     RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED},
    TRUE
  }
#endif /* FEATURE_HS_USB_DIGITAL_AUDIO_DEVICE */
  ,{ /* DIAG & Net device */
    HSU_CONF_SEL_DIAG_STD_NET_COMP,
    EFS_HSU_STD_NET,
    HSU_PROD_ID_DIAG_STD_NET,
    HSU_STANDARD_CMP_ONLY,
    {0,1,0,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, NET1_HSU_IFACE},
    1,
    {RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED,
    RDM_USB_NET_WWAN_DEV, RDM_SRVC_NOT_ALLOWED},
    HSU_ECM_COMP_IS_VALID & HSU_STANDARD_ECM_COMP_IS_VALID
  }
#if (defined FEATURE_HS_USB_MS_FD)
  ,{/* DIAG & NMEA & MS & MDM & Net device1 & Net device2 & Net device3 */ 
    HSU_CONF_SEL_DIAG_NMEA_MS_MDM_NET3_COMP,
    EFS_HSU_DIAG_NMEA_MS_MDM_NET3,
    HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_MS_MDM_NET3,
    HSU_PROPRIETARY_CMP_ONLY,
    {1,2,1,3,0,0,0,0,0},
    {DIAG_HSU_IFACE, NMEA_HSU_IFACE, MS_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE,
      NET2_HSU_IFACE, NET3_HSU_IFACE}
    5,
    {RDM_USB_MMC_DEV, RDM_USB_DIAG_DEV, RDM_USB_NMEA_DEV, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  }
  ,{/* DIAG & NMEA & MS & STD-MDM & STD-Net*/ 
    HSU_CONF_SEL_DIAG_NMEA_MS_STD_MDM_STD_NET_COMP,
    EFS_HSU_DIAG_NMEA_MS_STD_MDM_STD_NET,
    HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_MS_STD_MDM_STD_NET,
    HSU_STANDARD_CMP_ONLY,
    {1,2,1,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, NMEA_HSU_IFACE, MS_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE}
    5,
    {RDM_USB_MMC_DEV, RDM_USB_DIAG_DEV, RDM_USB_NMEA_DEV, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID & HSU_STANDARD_ECM_COMP_IS_VALID
  }
#endif /* FEATURE_HS_USB_MS_FD */
#ifdef T_UNDP
  ,
  { /* NET_DIAG & MDM & NMEA device */
    HSU_CONF_SEL_NET_DIAG_MDM_NMEA_COMP,
    EFS_HSU_NET_DIAG_MDM_NMEA,
    HSU_PROD_ID_SINGLE_IF_NET_DIAG_MDM_NMEA,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,2,1,1,0,0,0,0,0},
    {NET1_HSU_IFACE, DIAG_HSU_IFACE, MDM_HSU_IFACE, NMEA_HSU_IFACE},
    4,
    {RDM_USB_DIAG_DEV, RDM_USB_MDM_DEV, 
     RDM_USB_NET_WWAN_DEV, RDM_USB_NMEA_DEV, RDM_SRVC_NOT_ALLOWED},
    TRUE
  }
  ,
  { /* NET_DIAG & MDM device */
    HSU_CONF_SEL_NET_DIAG_MDM_COMP,
    EFS_HSU_NET_DIAG_MDM,
    HSU_PROD_ID_SINGLE_IF_NET_DIAG_MDM,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,1,1,1,0,0,0,0,0},
    {NET1_HSU_IFACE, DIAG_HSU_IFACE, MDM_HSU_IFACE},
    3,
    {RDM_USB_DIAG_DEV, RDM_USB_MDM_DEV, 
     RDM_USB_NET_WWAN_DEV, RDM_SRVC_NOT_ALLOWED},
    TRUE
  }
  ,
  { /* NET_DIAG & NMEA device */
    HSU_CONF_SEL_NET_DIAG_NMEA_COMP,
    EFS_HSU_NET_DIAG_NMEA,
    HSU_PROD_ID_SINGLE_IF_NET_DIAG_NMEA,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,2,0,1,0,0,0,0,0},
    {NET1_HSU_IFACE, DIAG_HSU_IFACE, NMEA_HSU_IFACE},
    3,
    {RDM_USB_DIAG_DEV, RDM_USB_NET_WWAN_DEV, RDM_USB_NMEA_DEV, 
     RDM_SRVC_NOT_ALLOWED},
    TRUE
  }
  ,
  { /* NET_DIAG device */
    HSU_CONF_SEL_NET_DIAG_COMP,
    EFS_HSU_NET_DIAG,
    HSU_PROD_ID_SINGLE_IF_NET_DIAG,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,1,0,1,0,0,0,0,0},
    {NET1_HSU_IFACE, DIAG_HSU_IFACE},
    2,
    {RDM_USB_DIAG_DEV, RDM_USB_NET_WWAN_DEV, 
     RDM_SRVC_NOT_ALLOWED},
    TRUE
  }
#endif /* T_UNDP */
  ,{/* DIAG & NMEA & MDM & Net device1 & Net device2 & Net device3 */ 
    HSU_CONF_SEL_DIAG_NMEA_MDM_NET3_COMP,
    EFS_HSU_DIAG_NMEA_MDM_NET3,
    HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_MDM_NET3,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,2,1,3,0,0,0,0,0},
    {DIAG_HSU_IFACE, NMEA_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE, NET2_HSU_IFACE,
      NET3_HSU_IFACE},
    4,
    {RDM_USB_DIAG_DEV, RDM_USB_NMEA_DEV, RDM_USB_MDM_DEV, 
     RDM_USB_NET_WWAN_DEV, RDM_SRVC_NOT_ALLOWED},
    HSU_ECM_COMP_IS_VALID
  }

#ifdef FEATURE_HS_USB_BREWMP_COMPOSITION
  ,
  { /* BrewMP device */
    HSU_CONF_SEL_BREWMP_COMP,
    EFS_HSU_BREWMP_COMPOSITION,
    0,  /* Product ID is provided by the BrewMP layer */
    HSU_PROPRIETARY_CMP_ONLY,
    {0, 1},  /* FD instances are defined by the BrewMP layer.
             ** Initialized to DIAG-only composition,
             ** for allowing smooth USB stack startup.
             */
    {NO_HSU_IFACE}
    1,
    {RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
     RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED},
    FALSE
  }
#endif  /* FEATURE_HS_USB_BREWMP_COMPOSITION */

#ifdef FEATURE_HS_USB_MS_FD
  ,
    {/* DIAG & NMEA & MS & MDM & Net device1 & Net device2 */ 
      HSU_CONF_SEL_DIAG_NMEA_MS_MDM_NET2_COMP,
      EFS_HSU_DIAG_NMEA_MS_MDM_NET2,
      HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_MS_MDM_NET2,
      HSU_PROPRIETARY_CMP_ONLY,
      {1,2,1,2,0,0,0,0,0},
      {DIAG_HSU_IFACE, NMEA_HSU_IFACE, MS_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE,
        NET2_HSU_IFACE},
      5,
      {RDM_USB_MMC_DEV, RDM_USB_DIAG_DEV, RDM_USB_NMEA_DEV, 
       RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
      HSU_ECM_COMP_IS_VALID
    }

#endif  /* FEATURE_HS_USB_MS_FD */
  ,
  {/* DIAG & NMEA & MDM & Net device1 & Net device2 */ 
    HSU_CONF_SEL_DIAG_NMEA_MDM_NET2_COMP,
    EFS_HSU_DIAG_NMEA_MDM_NET2,
    HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_MDM_NET2,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,2,1,2,0,0,0,0,0},
    {DIAG_HSU_IFACE, NMEA_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE, NET2_HSU_IFACE},
    4,
    {RDM_USB_DIAG_DEV, RDM_USB_NMEA_DEV, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV, RDM_SRVC_NOT_ALLOWED},
     HSU_ECM_COMP_IS_VALID
  },
  {/* DIAG & NMEA & MDM & 4 Net devices */ 
    HSU_CONF_SEL_DIAG_NMEA_MDM_NET4_COMP,
    EFS_HSU_DIAG_NMEA_MDM_NET4,
    HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_MDM_NET4,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,2,1,4,0,0,0,0,0},
    {DIAG_HSU_IFACE, NMEA_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE, NET2_HSU_IFACE,
      NET3_HSU_IFACE, NET4_HSU_IFACE},
    4,
    {RDM_USB_DIAG_DEV, RDM_USB_NMEA_DEV, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV, RDM_SRVC_NOT_ALLOWED},
    HSU_ECM_COMP_IS_VALID
  },
  {/* DIAG & NMEA & MDM & 5 Net devices */ 
    HSU_CONF_SEL_DIAG_NMEA_MDM_NET5_COMP,
    EFS_HSU_DIAG_NMEA_MDM_NET5,
    HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_MDM_NET5,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,2,1,5,0,0,0,0,0},
    {DIAG_HSU_IFACE, NMEA_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE, NET2_HSU_IFACE,
      NET3_HSU_IFACE, NET4_HSU_IFACE, NET5_HSU_IFACE},
    4,
    {RDM_USB_DIAG_DEV, RDM_USB_NMEA_DEV, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV, RDM_SRVC_NOT_ALLOWED},
    HSU_ECM_COMP_IS_VALID
  },
  {
    /* Diag & NMEA & MDM & MBIM */
    HSU_CONF_SEL_DIAG_NMEA_MDM_MBIM_COMP,
    EFS_HSU_DIAG_NMEA_MDM_MBIM,
    HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_MDM_MBIM,
    HSU_GOBI_FUSION_CMP,
    {0,2,1,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, NMEA_HSU_IFACE, MDM_HSU_IFACE, MBIM_HSU_IFACE},
    4,
    {RDM_USB_DIAG_DEV, RDM_USB_NMEA_DEV, RDM_USB_MDM_DEV, 
     RDM_USB_NET_WWAN_DEV, RDM_SRVC_NOT_ALLOWED},
    HSU_ECM_COMP_IS_VALID
  },

  {/* DIAG & SER3 & SER4 & MDM & 5 Net devices */ 
    HSU_CONF_SEL_DIAG_SER3_SER4_MDM_NET5_COMP,
    EFS_HSU_DIAG_SER3_SER4_MDM_NET5,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER3_SER4_MDM_NET5,
    HSU_LA_FUSION_CMP,
    {0,3,1,5,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER3_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE,
      NET2_HSU_IFACE, NET3_HSU_IFACE, NET4_HSU_IFACE, NET5_HSU_IFACE},
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  {/* DIAG & SER3 & SER4 & MDM & CSVT & 4 Net devices */ 
    HSU_CONF_SEL_DIAG_SER3_SER4_MDM_CSVT_NET4_COMP,
    EFS_HSU_DIAG_SER3_SER4_MDM_CSVT_NET4,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER3_SER4_MDM_CSVT_NET4,
    HSU_LA_FUSION_CMP,
    {0,3,2,4,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER3_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE, CSVT_HSU_IFACE,
      NET1_HSU_IFACE, NET2_HSU_IFACE, NET3_HSU_IFACE, NET4_HSU_IFACE},
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  {
    /* Diag & SER3 & MDM & MBIM */
    HSU_CONF_SEL_DIAG_SER3_MDM_MBIM_COMP,
    EFS_HSU_DIAG_SER3_MDM_MBIM,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER3_MDM_MBIM,
    HSU_GOBI_FUSION_CMP,
    {0,2,1,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER3_HSU_IFACE, MDM_HSU_IFACE, MBIM_HSU_IFACE},
    3,
    {RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, RDM_USB_MDM_DEV, 
     RDM_USB_NET_WWAN_DEV, RDM_SRVC_NOT_ALLOWED},
    HSU_ECM_COMP_IS_VALID
  },

  {
    /* Diag & SER3 & MDM & NET */
    HSU_CONF_SEL_DIAG_SER3_MDM_NET_COMP,
    EFS_HSU_DIAG_SER3_MDM_NET,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER3_MDM_NET,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,2,1,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER3_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE},
    3,
    {RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, RDM_USB_MDM_DEV, 
     RDM_USB_NET_WWAN_DEV, RDM_SRVC_NOT_ALLOWED},
    HSU_ECM_COMP_IS_VALID
  },

  {
    /* Diag & SER3 & SER4 & MDM & MBIM */
    HSU_CONF_SEL_DIAG_SER3_SER4_MDM_MBIM_COMP,
    EFS_HSU_DIAG_SER3_SER4_MDM_MBIM,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER3_SER4_MDM_MBIM,
    HSU_GOBI_FUSION_CMP,
    {0,3,1,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER3_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE, MBIM_HSU_IFACE},
    3,
    {RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, RDM_USB_MDM_DEV, 
     RDM_USB_NET_WWAN_DEV, RDM_SRVC_NOT_ALLOWED},
    HSU_ECM_COMP_IS_VALID
  },

  {
    /* Diag & SER3 & SER4 & MDM & NET */
    HSU_CONF_SEL_DIAG_SER3_SER4_MDM_NET_COMP,
    EFS_HSU_DIAG_SER3_SER4_MDM_NET,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER3_SER4_MDM_NET,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,3,1,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER3_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE},
    3,
    {RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, RDM_USB_MDM_DEV, 
     RDM_USB_NET_WWAN_DEV, RDM_SRVC_NOT_ALLOWED},
    HSU_ECM_COMP_IS_VALID
  },


  {
    /* Diag & SER4 & MDM & NET5 */
    HSU_CONF_SEL_DIAG_SER4_MDM_NET5_COMP,
    EFS_HSU_DIAG_SER4_MDM_NET5,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER4_MDM_NET5,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,2,1,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE},
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  {/* DIAG & NMEA & MDM & 5 Net devices, This is to support MCCI driver which only support GOBI PID */ 
    HSU_CONF_SEL_DIAG_NMEA_MDM_NET5_UNDP_COMP,
    EFS_HSU_DIAG_NMEA_MDM_NET5_UNDP,
    HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_MDM_NET5_UNDP,
    HSU_UNDP_CMP_ONLY,
    {0,2,1,5,0,0,0,0,0},
    {DIAG_HSU_IFACE, NMEA_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE, NET2_HSU_IFACE,
      NET3_HSU_IFACE, NET4_HSU_IFACE, NET5_HSU_IFACE},
    4,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_USB_NMEA_DEV, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  {/* MBIM */ 
    HSU_CONF_SEL_MBIM_COMP,
    EFS_HSU_MBIM,
    HSU_PROD_ID_SINGLE_IF_MBIM,
    HSU_GOBI_FUSION_CMP,
    {0,0,0,1,0,0,0,0,0},
    {MBIM_HSU_IFACE},
    1,
    {RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, 
     RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  {/* NMEA & MBIM */ 
    HSU_CONF_SEL_NMEA_MBIM_COMP,
    EFS_HSU_NMEA_MBIM,
    HSU_PROD_ID_SINGLE_IF_NMEA_MBIM,
    HSU_GOBI_FUSION_CMP,
    {0,1,0,1,0,0,0,0,0},
    {NMEA_HSU_IFACE, MBIM_HSU_IFACE},
    2,
    {RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED,
      RDM_USB_NMEA_DEV, RDM_SRVC_NOT_ALLOWED, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  {/* SER3 & MBIM */ 
    HSU_CONF_SEL_SER3_MBIM_COMP,
    EFS_HSU_SER3_MBIM,
    HSU_PROD_ID_SINGLE_IF_SER3_MBIM,
    HSU_GOBI_FUSION_CMP,
    {0,1,0,1,0,0,0,0,0},
    {SER3_HSU_IFACE, MBIM_HSU_IFACE},
    1,
    {RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, 
     RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  {/* SER3 & SER4 & MBIM */ 
    HSU_CONF_SEL_SER3_SER4_MBIM_COMP,
    EFS_HSU_SER3_SER4_MBIM,
    HSU_PROD_ID_SINGLE_IF_SER3_SER4_MBIM,
    HSU_GOBI_FUSION_CMP,
    {0,2,0,1,0,0,0,0,0},
    {SER3_HSU_IFACE, SER4_HSU_IFACE, MBIM_HSU_IFACE},
    1,
    {RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, 
     RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  {/* DIAG + MDM + 8 NET */ 
    HSU_CONF_SEL_DIAG_MDM_NET8_COMP,
    EFS_HSU_DIAG_MDM_NET8,
    HSU_PROD_ID_SINGLE_IF_DIAG_MDM_NET8,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,1,1,8,0,0,0,0,0},
    {DIAG_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE, NET2_HSU_IFACE, NET3_HSU_IFACE,
      NET4_HSU_IFACE, NET5_HSU_IFACE, NET6_HSU_IFACE, NET7_HSU_IFACE, NET8_HSU_IFACE},
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, 
     RDM_USB_MDM_DEV, RDM_SRVC_NOT_ALLOWED, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  {/* DIAG + MDM + 6 NET */
    HSU_CONF_SEL_DIAG_MDM_NET6_COMP,
    EFS_HSU_DIAG_MDM_NET6,
    HSU_PROD_ID_SINGLE_IF_DIAG_MDM_NET6,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,1,1,6,0,0,0,0,0},
    {DIAG_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE, NET2_HSU_IFACE, NET3_HSU_IFACE,
      NET4_HSU_IFACE, NET5_HSU_IFACE, NET6_HSU_IFACE},
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, 
      RDM_USB_MDM_DEV, RDM_SRVC_NOT_ALLOWED, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  {/* DIAG & SER5 & SER4 & MDM & CSVT & 4 Net devices */ 
    HSU_CONF_SEL_DIAG_SER5_SER4_MDM_CSVT_NET4_COMP,
    EFS_HSU_DIAG_SER5_SER4_MDM_CSVT_NET4,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER5_SER4_MDM_CSVT_NET4,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,3,2,4,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER5_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE, CSVT_HSU_IFACE,
      NET1_HSU_IFACE, NET2_HSU_IFACE, NET3_HSU_IFACE, NET4_HSU_IFACE},
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },  

  {/* DIAG & SER4 & MDM & CSVT & 2 Net devices */ 
    HSU_CONF_SEL_DIAG_SER4_MDM_CSVT_NET2_COMP,
    EFS_HSU_DIAG_SER4_MDM_CSVT_NET2,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER4_MDM_CSVT_NET2,
    HSU_LA_FUSION_CMP,
    {0,2,2,2,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE, CSVT_HSU_IFACE,
      NET1_HSU_IFACE, NET2_HSU_IFACE},
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  {/* DIAG & SER3 & SER4 & MDM & 5 Net devices, This composition is same as 9048 */
    HSU_CONF_SEL_DIAG_SER3_SER4_MDM_NET5_COMP_2,
    EFS_HSU_DIAG_SER3_SER4_MDM_NET5_2,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER3_SER4_MDM_NET5_2,
    HSU_LA_FUSION_CMP,
    {0,3,1,5,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER3_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE,
      NET2_HSU_IFACE, NET3_HSU_IFACE, NET4_HSU_IFACE, NET5_HSU_IFACE},
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },
  
  {/* DIAG & SER3 & SER4 & MDM & CSVT & 4 Net devices, This composition is same as 904C */ 
    HSU_CONF_SEL_DIAG_SER3_SER4_MDM_CSVT_NET4_COMP_2,
    EFS_HSU_DIAG_SER3_SER4_MDM_CSVT_NET4_2,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER3_SER4_MDM_CSVT_NET4_2,
    HSU_LA_FUSION_CMP,
    {0,3,2,4,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER3_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE, CSVT_HSU_IFACE,
      NET1_HSU_IFACE, NET2_HSU_IFACE, NET3_HSU_IFACE, NET4_HSU_IFACE},
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  {/* DIAG + SER3 + MDM + MBIM + GNSS */
    HSU_CONF_SEL_DIAG_SER3_MDM_MBIM_GNSS_COMP,
    EFS_HSU_DIAG_SER3_MDM_MBIM_GNSS,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER3_MDM_MBIM_GNSS,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,2,1,2,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER3_HSU_IFACE, MDM_HSU_IFACE, MBIM_HSU_IFACE, GNSS_HSU_IFACE},
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV,
     RDM_SRVC_NOT_ALLOWED, RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
     HSU_ECM_COMP_IS_VALID
  },
    
  {/* DIAG + SER3 + SER4 + MDM + MBIM + GNSS */
    HSU_CONF_SEL_DIAG_SER3_SER4_MDM_MBIM_GNSS_COMP,
    EFS_HSU_DIAG_SER3_SER4_MDM_MBIM_GNSS,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER3_SER4_MDM_MBIM_GNSS,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,3,1,2,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER3_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE, MBIM_HSU_IFACE, GNSS_HSU_IFACE},
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV,
     RDM_SRVC_NOT_ALLOWED, RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },
    
  {/* SER3 + MBIM + GNSS */
     HSU_CONF_SEL_SER3_MBIM_GNSS_COMP,
     EFS_HSU_SER3_MBIM_GNSS,
     HSU_PROD_ID_SINGLE_IF_SER3_MBIM_GNSS,
     HSU_PROPRIETARY_CMP_ONLY,
     {0,1,0,2,0,0,0,0,0},
     {SER3_HSU_IFACE, MBIM_HSU_IFACE, GNSS_HSU_IFACE},
     1,
     {RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED,
      RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, RDM_USB_NET_WWAN_DEV},
     HSU_ECM_COMP_IS_VALID
  },
   
  {/* SER3 + SER4 + MBIM + GNSS */
     HSU_CONF_SEL_SER3_SER4_MBIM_GNSS_COMP,
     EFS_HSU_SER3_SER4_MBIM_GNSS,
     HSU_PROD_ID_SINGLE_IF_SER3_SER4_MBIM_GNSS,
     HSU_PROPRIETARY_CMP_ONLY,
     {0,2,0,2,0,0,0,0,0},
     {SER3_HSU_IFACE, SER4_HSU_IFACE, MBIM_HSU_IFACE, GNSS_HSU_IFACE},
     1,
     {RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED,
       RDM_SRVC_NOT_ALLOWED, RDM_SRVC_NOT_ALLOWED, RDM_USB_NET_WWAN_DEV},
     HSU_ECM_COMP_IS_VALID
  },

  {/* DIAG & SER3 & SER4 & MDM & CSVT & 2 Net devices */
     HSU_CONF_SEL_DIAG_SER3_SER4_MDM_CSVT_NET2_COMP,
     EFS_HSU_DIAG_SER3_SER4_MDM_CSVT_NET2,
     HSU_PROD_ID_SINGLE_IF_DIAG_SER3_SER4_MDM_CSVT_NET2,
     HSU_LA_FUSION_CMP,
     {0,3,2,2,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER3_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE, CSVT_HSU_IFACE,
      NET1_HSU_IFACE, NET2_HSU_IFACE},
     3,
     {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
      RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
      HSU_ECM_COMP_IS_VALID
  },

  {
     /* Diag & SER4 & MDM & NET4 */
     HSU_CONF_SEL_DIAG_SER4_MDM_NET4_COMP,
     EFS_HSU_DIAG_SER4_MDM_NET4,
     HSU_PROD_ID_SINGLE_IF_DIAG_SER4_MDM_NET4,
     HSU_PROPRIETARY_CMP_ONLY,
     {0,2,1,4,0,0,0,0,0},
     {DIAG_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE, NET2_HSU_IFACE,
       NET3_HSU_IFACE, NET4_HSU_IFACE},
     3,
     {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
       RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
     HSU_ECM_COMP_IS_VALID
  },

  {/* DIAG + SER4 + QDSS + MDM + 5 NET */ 
    HSU_CONF_SEL_DIAG_SER4_QDSS_MDM_NET5_COMP,
    EFS_HSU_DIAG_SER4_QDSS_MDM_NET5,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER4_QDSS_MDM_NET5,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,3,1,5,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER4_HSU_IFACE, QDSS_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE,
      NET2_HSU_IFACE, NET3_HSU_IFACE, NET4_HSU_IFACE, NET5_HSU_IFACE},
     3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },
     
  {
    /* Diag & SER4 & MDM & NET5, This is to support Host driver which only support GOBI PID */
    HSU_CONF_SEL_DIAG_SER4_MDM_NET5_UNDP_COMP,
    EFS_HSU_DIAG_SER4_MDM_NET5_UNDP,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER4_MDM_NET5_UNDP,
    HSU_UNDP_CMP_ONLY,
    {0,2,1,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE},
     3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  {/* DIAG & SER3 & SER4 & MDM & CSVT & 2 Net + IPCRouter devices */
     HSU_CONF_SEL_DIAG_SER3_SER4_MDM_CSVT_NET2_IPCR_COMP,
     EFS_HSU_DIAG_SER3_SER4_MDM_CSVT_NET2_IPCR,
     HSU_PROD_ID_SINGLE_IF_DIAG_SER3_SER4_MDM_CSVT_NET2_IPCR,
     HSU_LA_FUSION_CMP,
     {0,3,2,3,0,0,0,0,0},
     {DIAG_HSU_IFACE, SER3_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE, CSVT_HSU_IFACE,
      NET1_HSU_IFACE, NET2_HSU_IFACE, IPCR_HSU_IFACE},
     3,
     {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
      RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
     TRUE
  },

  {/* DIAG & DCI & SER3 & SER4 & QDSS & MDM & CSVT & 1 Net & 2 Net + IPCRouter devices */
     HSU_CONF_SEL_DIAG_DCI_SER3_SER4_QDSS_MDM_CSVT_NET1_NET2_IPCR_COMP,
     EFS_HSU_DIAG_DCI_SER3_SER4_QDSS_MDM_CSVT_NET1_NET2_IPCR,
     HSU_PROD_ID_SINGLE_IF_DIAG_DCI_SER3_SER4_QDSS_MDM_CSVT_NET1_NET2_IPCR,
     HSU_LA_FUSION_CMP,
     {0,5,2,3,0,0,0,0,0},
     {DIAG_HSU_IFACE, DCI_HSU_IFACE, SER3_HSU_IFACE, SER4_HSU_IFACE, QDSS_HSU_IFACE, 
      MDM_HSU_IFACE, CSVT_HSU_IFACE, NET1_HSU_IFACE, NET2_HSU_IFACE, IPCR_HSU_IFACE},
     3,
     {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
      RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
     TRUE
  },

  {
    /* Diag & SER4 & MDM & NET2 */
    HSU_CONF_SEL_DIAG_SER4_MDM_NET2_COMP,
    EFS_HSU_DIAG_SER4_MDM_NET2,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER4_MDM_NET2,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,2,1,2,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE, NET2_HSU_IFACE},
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    TRUE
  },

  {/* DIAG & SER4 & MDM & 2 Net + LWIP devices */
     HSU_CONF_SEL_DIAG_SER4_MDM_NET2_LWIP_COMP,
     EFS_HSU_DIAG_SER4_MDM_NET2_LWIP,
     HSU_PROD_ID_SINGLE_IF_DIAG_SER4_MDM_NET2_LWIP,
     HSU_PROPRIETARY_CMP_ONLY,
     {0,2,1,3,0,0,0,0,0},
     {DIAG_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE,
      NET1_HSU_IFACE, NET2_HSU_IFACE, LWIP_HSU_IFACE},
     3,
     {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
      RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
     TRUE
  },

  // 0x909C - DIAG + SER3 (SYS_M) + SER4 (EFS sync) + DUN + CSVT
  {
     HSU_CONF_SEL_DIAG_SER3_SER4_MDM_CSVT_COMP,
     EFS_HSU_DIAG_SER3_SER4_MDM_CSVT,
     HSU_PROD_ID_SINGLE_IF_DIAG_SER3_SER4_MDM_CSVT,
     HSU_LA_FUSION_CMP,
     {0,3,2,0,0,0,0,0,0},
     {
       DIAG_HSU_IFACE, SER3_HSU_IFACE, SER4_HSU_IFACE, 
       MDM_HSU_IFACE, CSVT_HSU_IFACE
     },
     3,
     {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
     HSU_ECM_COMP_IS_VALID
  },

  // 0x909D - DIAG + SER3 (SYS_M) + SER4 (EFS sync) + DUN + CSVT + IPCR
  {
    HSU_CONF_SEL_DIAG_SER3_SER4_MDM_CSVT_IPCR_COMP,
    EFS_HSU_DIAG_SER3_SER4_MDM_CSVT_IPCR,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER3_SER4_MDM_CSVT_IPCR,
    HSU_LA_FUSION_CMP,
    {0,3,2,1,0,0,0,0,0},
    {
      DIAG_HSU_IFACE, SER3_HSU_IFACE, SER4_HSU_IFACE,
      MDM_HSU_IFACE, CSVT_HSU_IFACE, 
      IPCR_HSU_IFACE
    },                  
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    TRUE
  },

  // 0x909E - DIAG + DCI + SER3 (SYS_M) + SER4 (EFS sync) + QDSS Trace (Bulk IN only) + DUN +
  // CSVT + IPCR (used for LA FUSION 4.5 superset without RmNET)
  {
    HSU_CONF_SEL_DIAG_DCI_SER3_SER4_QDSS_MDM_CSVT_IPCR,
    EFS_HSU_DIAG_DCI_SER3_SER4_QDSS_MDM_CSVT_IPCR,
    HSU_PROD_ID_SINGLE_IF_DIAG_DCI_SER3_SER4_QDSS_MDM_CSVT_IPCR,
    HSU_LA_FUSION_NO_ECM_CMP,
    {0,5,2,1,0,0,0,0,0},
    {
      DIAG_HSU_IFACE, DCI_HSU_IFACE, SER3_HSU_IFACE, SER4_HSU_IFACE, QDSS_HSU_IFACE, 
      MDM_HSU_IFACE, CSVT_HSU_IFACE, 
      IPCR_HSU_IFACE
    },
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
    RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    TRUE
  },

  // This PID uses Interrupt IN Endpoints. Similar to 0x9075.
  // 0x909F - DIAG + SER3 + SER4 (EFS sync) + MDM + CSVT + NET1_MUX + NET2_MUX
  {
    HSU_CONF_SEL_DIAG_SER3_SER4_MDM_CSVT_NET2_INTR_COMP,
    EFS_HSU_DIAG_SER3_SER4_MDM_CSVT_NET2_INTR,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER3_SER4_MDM_CSVT_NET2_INTR,
    HSU_LA_FUSION_BULK_TO_INT_IN_CMP,
    {0,3,2,2,0,0,0,0,0},
    {
      DIAG_HSU_IFACE, SER3_HSU_IFACE, SER4_HSU_IFACE, 
      MDM_HSU_IFACE, CSVT_HSU_IFACE,
      NET1_HSU_IFACE, NET2_HSU_IFACE
    },
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  // This PID uses Interrupt IN Endpoints. 
  // 0x90A0 - DIAG + SER3 + SER4 (EFS sync) + MDM + CSVT + NET1_MUX + NET2_MUX + IPCR
  {
    HSU_CONF_SEL_DIAG_SER3_SER4_MDM_CSVT_NET2_IPCR_INTR_COMP,
    EFS_HSU_DIAG_SER3_SER4_MDM_CSVT_NET2_IPCR_INTR,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER3_SER4_MDM_CSVT_NET2_IPCR_INTR,
    HSU_LA_FUSION_BULK_TO_INT_IN_CMP,
    {0,3,2,3,0,0,0,0,0},
    {
      DIAG_HSU_IFACE, SER3_HSU_IFACE, SER4_HSU_IFACE, 
      MDM_HSU_IFACE, CSVT_HSU_IFACE,
      NET1_HSU_IFACE, NET2_HSU_IFACE, IPCR_HSU_IFACE
    },
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  // 0x90A4 - DIAG + DCI + SER3 + SER4 (EFS sync) + QDSS + MDM + CSVT + NET1_MUX + NET2_MUX + IPCR
  {
    HSU_CONF_SEL_DIAG_DCI_SER3_SER4_QDSS_MDM_CSVT_NET2_IPCR_INTR_COMP,
    EFS_HSU_DIAG_DCI_SER3_SER4_QDSS_MDM_CSVT_NET2_IPCR_INTR,
    HSU_PROD_ID_SINGLE_IF_DIAG_DCI_SER3_SER4_QDSS_MDM_CSVT_NET2_IPCR_INTR,
    HSU_LA_FUSION_BULK_TO_INT_IN_CMP,
    {0,5,2,3,0,0,0,0,0},
    {
      DIAG_HSU_IFACE, DCI_HSU_IFACE, SER3_HSU_IFACE, SER4_HSU_IFACE, QDSS_HSU_IFACE,
      MDM_HSU_IFACE, CSVT_HSU_IFACE,
      NET1_HSU_IFACE, NET2_HSU_IFACE, IPCR_HSU_IFACE
    },
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  // 0x90A5 -DIAG + SER4 (EFS sync) + DUN(MDM) + NET1_MUX 
  {
    HSU_CONF_SEL_DIAG_SER4_MDM_NET1_COMP,
    EFS_HSU_DIAG_SER4_MDM_NET1,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER4_MDM_NET1,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,2,1,1,0,0,0,0,0},
    {
      DIAG_HSU_IFACE, SER4_HSU_IFACE,
      MDM_HSU_IFACE,
      NET1_HSU_IFACE
    },
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  // 0x90A6 - DIAG + SER4 (EFS sync) + QDSS + DUN(MDM) + NET1_MUX 
  {
    HSU_CONF_SEL_DIAG_SER4_QDSS_MDM_NET1_MUX_COMP,
    EFS_HSU_DIAG_SER4_QDSS_MDM_NET1_MUX,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER4_QDSS_MDM_NET1_MUX,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,3,1,1,0,0,0,0,0},
    {
      DIAG_HSU_IFACE, SER4_HSU_IFACE, QDSS_HSU_IFACE,
      MDM_HSU_IFACE,
      NET1_HSU_IFACE,
    },
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  // 0x90A8 - DIAG + SER4 (EFS sync) + QDSS + DUN(MDM) + NET1
  {
    HSU_CONF_SEL_DIAG_SER4_QDSS_MDM_NET1_COMP,
    EFS_HSU_DIAG_SER4_QDSS_MDM_NET1,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER4_QDSS_MDM_NET1,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,3,1,1,0,0,0,0,0},
    {
      DIAG_HSU_IFACE, SER4_HSU_IFACE, QDSS_HSU_IFACE,
      MDM_HSU_IFACE,
      NET1_HSU_IFACE,
    },
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },

  // 0x90AB - DIAG + SER4 (EFS sync) + QDSS (Bulk IN only) + DUN(MDM) + NET1 (no MUX) + DPL (Bulk IN)
  {
    HSU_CONF_SEL_DIAG_SER4_QDSS_MDM_NET1_DPL_COMP,
    EFS_HSU_DIAG_SER4_QDSS_MDM_NET1_DPL,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER4_QDSS_MDM_NET1_DPL,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,3,1,2,0,0,0,0,0},
    {
      DIAG_HSU_IFACE, SER4_HSU_IFACE, QDSS_HSU_IFACE,
      MDM_HSU_IFACE,
      NET1_HSU_IFACE, DPL_HSU_IFACE,
    },
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
    RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV}, // TODO RDM enum may need modification
    HSU_ECM_COMP_IS_VALID
  },

#ifdef FEATURE_HS_USB_DIGITAL_AUDIO_DEVICE  
  // 0x90A8 - DIAG + SER4 (EFS sync) + QDSS + DUN(MDM) + NET1 + AUDIO
  {
    HSU_CONF_SEL_DIAG_SER4_QDSS_MDM_NET1_AUDIO_COMP,
    EFS_HSU_DIAG_SER4_QDSS_MDM_NET1_AUDIO,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER4_QDSS_MDM_NET1_AUDIO,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,3,1,1,0,0,0,0,1},
    {
      DIAG_HSU_IFACE, SER4_HSU_IFACE, QDSS_HSU_IFACE,
      MDM_HSU_IFACE,
      NET1_HSU_IFACE,
      AUDIO_HSU_IFACE,
    },
    4,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV, RDM_USB_AUDIO_DEV},
    HSU_ECM_COMP_IS_VALID
  },
#endif 

  // 0x90B2 - DIAG + QDSS Trace (Bulk IN) + DUN(MDM) + NET1 (no MUX)
  {
    HSU_CONF_SEL_DIAG_QDSS_MDM_NET1_COMP,  
    EFS_HSU_DIAG_QDSS_MDM_NET1,       
    HSU_PROD_ID_SINGLE_IF_DIAG_QDSS_MDM_NET1, 
    HSU_PROPRIETARY_CMP_ONLY,    
    {0,2,1,1,0,0,0,0,0},
    {
      DIAG_HSU_IFACE, QDSS_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE,  
    },
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
    RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV}, 
    HSU_ECM_COMP_IS_VALID
  },

  // 0x90C2 - DIAG + NMEA + DUN(MDM) + NET1 (no MUX) + DPL
  {
    HSU_CONF_SEL_DIAG_NMEA_MDM_NET1_DPL_COMP,  
    EFS_HSU_DIAG_NMEA_MDM_NET_DPL,
    HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_MDM_NET1_DPL, 
    HSU_PROPRIETARY_CMP_ONLY,    
    {0,2,1,2,0,0,0,0,0},
    {
      DIAG_HSU_IFACE, NMEA_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE, DPL_HSU_IFACE,
    },
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
    RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV}, 
    HSU_ECM_COMP_IS_VALID
  },

  // 0x90C2 - DIAG + SER4 (EFS SYNC) + DUN(MDM) + NET1 (no MUX) + DPL
  {
    HSU_CONF_SEL_DIAG_SER4_MDM_NET1_DPL_COMP,  
    EFS_HSU_DIAG_SER4_MDM_NET_DPL,
    HSU_PROD_ID_SINGLE_IF_DIAG_SER4_MDM_NET1_DPL, 
    HSU_PROPRIETARY_CMP_ONLY,    
    {0,2,1,2,0,0,0,0,0},
    {
      DIAG_HSU_IFACE, SER4_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE, DPL_HSU_IFACE,
    },
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED,
    RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV}, 
    HSU_ECM_COMP_IS_VALID
  },
  { /* DIAG & NMEA & QDSS & MDM & Net device (No Mux)*/
    HSU_CONF_SEL_DIAG_NMEA_QDSS_MDM_NET1_COMP,
    EFS_HSU_DIAG_NMEA_QDSS_MDM_NET1,
    HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_QDSS_MDM_NET1,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,3,1,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, NMEA_HSU_IFACE, QDSS_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE},
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },
  { /* DIAG & NMEA & QDSS & MDM & Net device (No Mux)*/
    HSU_CONF_SEL_DIAG_NMEA_QDSS_MDM_NET1_MUX_COMP,
    EFS_HSU_DIAG_NMEA_QDSS_MDM_NET1_MUX,
    HSU_PROD_ID_SINGLE_IF_DIAG_NMEA_QDSS_MDM_NET1_MUX,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,3,1,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, NMEA_HSU_IFACE, QDSS_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE},
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },
  { /* DIAG & SER3 & SER5 & DUN(MDM) & NET1 (no MUX)*/
    HSU_CONF_SEL_DIAG_SER3_SER5_MDM_NET1_COMP,
    EFS_HSU_DIAG_SER3_SER5_MDM_NET1,
    HSU_PROD_ID_SINGLE_IFC_DIAG_SER3_SER5_MDM_NET1,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,3,1,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER3_HSU_IFACE, SER5_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE},
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },
  { /* DIAG & SER3 & SER5 & SER6 & DUN(MDM) & NET1 (no MUX)*/
    HSU_CONF_SEL_DIAG_SER3_SER5_SER6_MDM_NET1_COMP,
    EFS_HSU_DIAG_SER3_SER5_SER6_MDM_NET1,
    HSU_PROD_ID_SINGLE_IFC_DIAG_SER3_SER5_SER6_MDM_NET1,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,4,1,1,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER3_HSU_IFACE, SER5_HSU_IFACE, SER6_HSU_IFACE, MDM_HSU_IFACE, NET1_HSU_IFACE},
    3,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
     RDM_USB_MDM_DEV, RDM_USB_NET_WWAN_DEV},
    HSU_ECM_COMP_IS_VALID
  },
  { /* DIAG & SER3 & SER5 & SER6 & DUN(MDM) */
    HSU_CONF_SEL_DIAG_SER3_SER5_SER6_MDM_COMP,
    EFS_HSU_DIAG_SER3_SER5_SER6_MDM,
    HSU_PROD_ID_SINGLE_IFC_DIAG_SER3_SER5_SER6_MDM,
    HSU_PROPRIETARY_CMP_ONLY,
    {0,4,1,0,0,0,0,0,0},
    {DIAG_HSU_IFACE, SER3_HSU_IFACE, SER5_HSU_IFACE, SER6_HSU_IFACE, MDM_HSU_IFACE},
    2,
    {RDM_SRVC_NOT_ALLOWED, RDM_USB_DIAG_DEV, RDM_SRVC_NOT_ALLOWED, 
     RDM_USB_MDM_DEV},
    HSU_ECM_COMP_IS_VALID
  },
};

/*
 * The NV value for the default composition. 
 * This is used in case the NV item is not initialized properly on the phone. 
 */

    const hsu_composition_enum default_std_comp_nv_value =  EFS_HSU_DIAG_NMEA_MS_STD_MDM_STD_NET; 
  #ifdef FEATURE_HS_USB_F3
    static hsu_composition_enum default_comp_nv_value = EFS_HSU_DIAG_SER4_MDM_NET5;
  #elif defined(FEATURE_GOBI)
    static hsu_composition_enum default_comp_nv_value = EFS_HSU_NET_DIAG_MDM_NMEA;
  #else
    static hsu_composition_enum default_comp_nv_value = EFS_HSU_DIAG_NMEA_MDM_NET;
  #endif /* FEATURE_HS_USB_F3 */

/*==============================================================================

                          FUNCTION DECLARATIONS FOR MODULE
  
==============================================================================*/
/*==============================================================================

FUNCTION          HSU_CONF_SEL_COMP_UTILS_COMP_ID_IS_VALID_FOR_HSU

DESCRIPTION
  Checks if the given value is a valid composition ID for HS-US.

DEPENDENCIES
  None.

RETURN VALUE
  TRUE if valid, FALSE otherwise.

SIDE EFFECTS
  None. 

==============================================================================*/
boolean hsu_conf_sel_comp_utils_comp_id_is_valid_for_hsu
(
  hsu_composition_enum efs_comp_id
)
{
  uint8 i;

#ifdef FEATURE_HS_USB_MEM_OPTIMIZATION
  switch(efs_comp_id)
  {
    case  EFS_HSU_MS:
    case  EFS_HSU_DIAG_MDM:
    case  EFS_HSU_DIAG_MS:
      /* only these compositions are supported and go through to normal 
            * operation to find corresponding composition */
      break;

    default:
      /* The other compositions are not supported. return with false immediately */
      return FALSE;
  }
#endif /* FEATURE_HS_USB_MEM_OPTIMIZATION */

  for( i = 0 ; i < (uint8)HSU_CONF_SEL_NUM_OF_COMPS ; ++i)
  {
    if(compositions_details[i].efs_comp_id == efs_comp_id && compositions_details[i].comp_is_supported)
    {
      return TRUE;
    }
  }
  return FALSE;
}/* hsu_conf_sel_comp_utils_comp_id_is_valid_for_hsu */

/*==============================================================================

FUNCTION          HSU_CONF_SEL_COMP_UTILS_GET_COMP_DETAILS

DESCRIPTION
  This function returns a pointer to the information relevant for the given 
  composition ID.

DEPENDENCIES
  None.

RETURN VALUE
  Pointer to hsu_conf_sel_comp_info_type for success, 
  on failures returns NULL.

SIDE EFFECTS
  None.

==============================================================================*/
const hsu_conf_sel_comp_info_type * hsu_conf_sel_comp_utils_get_comp_details
(
  hsu_composition_enum nv_composition_id
)
{
  uint16 i;

  for( i = 0 ; i < (uint8)HSU_CONF_SEL_NUM_OF_COMPS ; ++i )
  {
    if(compositions_details[i].efs_comp_id == nv_composition_id && compositions_details[i].comp_is_supported)
    {
      return &compositions_details[i];
    }
  }
  HSU_MSG_ERROR_1("*_get_comp_details(): Invalid NV composition ID %d.", 
    nv_composition_id);
  return NULL; 
} /* hsu_conf_sel_comp_utils_get_comp_details */

/*==============================================================================

FUNCTION          HSU_CONF_SEL_COMP_UTILS_GET_COMP_DETAILS_BY_HSU_ID

DESCRIPTION
  This function returns a pointer to the information relevant for the given 
  HSU composition ID.

DEPENDENCIES
  None.

RETURN VALUE
  Pointer to hsu_conf_sel_comp_info_type for success, 
  on failures returns NULL.

SIDE EFFECTS
  None.

==============================================================================*/
const hsu_conf_sel_comp_info_type * 
  hsu_conf_sel_comp_utils_get_comp_details_by_hsu_id
(
  hsu_conf_sel_composition_id_enum hsu_comp_id
)
{
  if (hsu_comp_id < HSU_CONF_SEL_NUM_OF_COMPS && compositions_details[hsu_comp_id].hsu_comp_id == hsu_comp_id
      && compositions_details[hsu_comp_id].comp_is_supported)
  {
    return &compositions_details[hsu_comp_id];
  }
  HSU_MSG_ERROR_1(
      "*_get_comp_details_by_hsu_id(): hsu_conf_sel_comp_utils_get_comp_details_by_hsu_id failed, hsu_comp_id=%d",hsu_comp_id);
  return NULL;
} /* hsu_conf_sel_comp_utils_get_comp_details */

/*==============================================================================

FUNCTION          HSU_CONF_SEL_COMP_UTILS_GET_COMP_DETAILS_BY_PID

DESCRIPTION
  This function returns a pointer to the information relevant for the given 
  Product ID (PID).

DEPENDENCIES
  None.

RETURN VALUE
  Pointer to hsu_conf_sel_comp_info_type for success, 
  on failures returns NULL.

SIDE EFFECTS
  None.

==============================================================================*/
const hsu_conf_sel_comp_info_type * 
  hsu_conf_sel_comp_utils_get_comp_details_by_pid
(
  uint16 product_id
)
{
  uint32  comp_table_index;

  for (comp_table_index = 0;
       comp_table_index < HSU_CONF_SEL_NUM_OF_COMPS;
       comp_table_index++)
  {
    if (compositions_details[comp_table_index].product_id == product_id)
    {
      return &compositions_details[comp_table_index];
    }
  }
  
  HSU_MSG_ERROR_1(
      "*_get_comp_details_by_pid(): failed, pid=%d", product_id);

  return NULL;
} /* hsu_conf_sel_comp_utils_get_comp_details_by_pid */

/*==============================================================================

FUNCTION          HSU_CONF_SEL_COMP_UTILS_GET_DEFAULT_COMP_INFO

DESCRIPTION
  Returns the composition info for the default composition. 

DEPENDENCIES
  None.

RETURN VALUE
  Pointer to the default composition's info for success,
  on failures returns NULL.

SIDE EFFECTS
  None. 

==============================================================================*/
const hsu_conf_sel_comp_info_type * 
  hsu_conf_sel_comp_utils_get_default_comp_info(void)
{
  const hsu_conf_sel_comp_info_type * default_comp_info = 
      hsu_conf_sel_comp_utils_get_comp_details(default_comp_nv_value);
  if(default_comp_info == NULL)
  {
    HSU_MSG_ERROR_1(
      "*_get_default_comp_info(): hsu_conf_sel_comp_utils_get_default_comp_info failed, default_comp=%d",default_comp_nv_value);
    return NULL;
  }
  return default_comp_info;
}/* hsu_conf_sel_comp_utils_get_default_comp_info */

#ifdef FEATURE_HS_USB_STANDARD_ECM
/*==============================================================================

FUNCTION          HSU_CONF_SEL_COMP_UTILS_GET_DEFAULT_STD_COMP_INFO

DESCRIPTION
Returns the default composition info for an OS that supports standard driver 
composition. 

DEPENDENCIES
None.

RETURN VALUE
Pointer to the default standard composition's info for success,
on failures returns NULL.

SIDE EFFECTS
None. 

==============================================================================*/
const hsu_conf_sel_comp_info_type * 
  hsu_conf_sel_comp_utils_get_default_std_comp_info(void)
{
  const hsu_conf_sel_comp_info_type * default_std_comp_info = 
    hsu_conf_sel_comp_utils_get_comp_details(default_std_comp_nv_value);
  if(default_std_comp_info == NULL)
  {
    HSU_MSG_ERROR_1(
      "*_get_default_std_comp_info(): hsu_conf_sel_comp_utils_get_comp_details failed, default_std_comp=%d",
      default_std_comp_nv_value);
    return NULL;
  }
  return default_std_comp_info;
}/* hsu_conf_sel_comp_utils_get_default_std_comp_info */
#endif /* FEATURE_HS_USB_STANDARD_ECM */


#ifdef FEATURE_HS_USB_BREWMP_COMPOSITION
/*==============================================================================

FUNCTION          HSU_CONF_SEL_COMP_UTILS_SET_COMP_INFO

DESCRIPTION
Set a specific composition info entry in the supported compositions table.

DEPENDENCIES
None.

RETURN VALUE
True for success, False for failure.

SIDE EFFECTS
None. 

==============================================================================*/
boolean hsu_conf_sel_comp_utils_set_comp_info(
  hsu_conf_sel_composition_id_enum  hsu_comp_id,
    /* The ID of the updated composition */

  uint16 product_id,
    /* Desired product ID for the composition */

  uint8  num_of_instances_per_fd[HSU_CFG_SEL_NUM_OF_FD_TYPES],
    /* Function drivers included in the composition */

  uint8  num_of_rdm_dev_in_comp,                   
    /* Number of RDM devices used */

  rdm_device_enum_type rdm_devices[HSU_NUM_OF_RDM_USB_PORTS]
    /* RDM devices used */
)
{
  uint32  comp_table_index;
  uint32  rdm_device_index;
  uint32  fd_type_index;


  for (comp_table_index = 0;
       comp_table_index < HSU_CONF_SEL_NUM_OF_COMPS;
       comp_table_index++)
  {
    if (compositions_details[comp_table_index].hsu_comp_id == hsu_comp_id)
    {
      break;
    }
  }

  /* The composition ID was not found in the composition table. */
  if (comp_table_index == HSU_CONF_SEL_NUM_OF_COMPS)
  {
    return FALSE;
  }

  /* Copy RDM devices info. */
  for (rdm_device_index = 0; 
       rdm_device_index < HSU_NUM_OF_RDM_USB_PORTS;
       rdm_device_index++)
  {
    compositions_details[comp_table_index].rdm_devices[rdm_device_index] = 
      rdm_devices[rdm_device_index];
  }

  compositions_details[comp_table_index].num_of_rdm_dev_in_comp = 
    num_of_rdm_dev_in_comp;

  /* Update the composition's function drivers. */
  for (fd_type_index = 0; 
       fd_type_index < HSU_CFG_SEL_NUM_OF_FD_TYPES;
       fd_type_index++)
  {
    compositions_details[comp_table_index].
      num_of_fd_instances_in_comp[fd_type_index] = 
        num_of_instances_per_fd[fd_type_index];
  }

  /* Set the product ID asociated with the composition. */
  compositions_details[comp_table_index].product_id = product_id;

  return TRUE;
}  /* hsu_conf_sel_comp_utils_set_comp_info */
#endif  /* FEATURE_HS_USB_BREWMP_COMPOSITION */
/*==============================================================================

FUNCTION          HSU_CONF_SEL_COMP_UTILS_UPDATE_DEFAULT_COMP_NV_VALUE

DESCRIPTION
Update the default_comp_nv_value based on platform detect for GOBI or LA Fusion.

DEPENDENCIES
None.

RETURN VALUE
True for success, False for failure.

SIDE EFFECTS
None. 

==============================================================================*/
void hsu_conf_sel_comp_utils_update_default_comp_nv_value(hsu_composition_enum nv_value)
{
  if(nv_value < EFS_HSU_NO_DEVICE)
  {
    default_comp_nv_value = nv_value;
    return;
  }
  HSU_ULOG_1(NO_MSG, DATA_LOG, "nv_value_greater_than_limit, nv_value %u", nv_value);
}

