/*===========================================================================

FILE:        u_data.c

DESCRIPTION: This file implements the target-specific icb micro driver data

   Copyright (c) 2019 QUALCOMM Technologies, Incorporated.
             All Rights Reserved
             QUALCOMM Proprietary
-------------------------------------------------------------------------------

$Header: //components/rel/core.tz/2.1.3/settings/systemdrivers/icb/config/9205/u_data.c#1 $ 
$DateTime: 2019/05/23 05:43:45 $
$Author: pwbldsvc $
$Change: 19292165 $

                      EDIT HISTORY FOR FILE

 Autogenerated for target: Trustzone
 This file was generated using Autogen script: 
 gen.py

 when         who     what, where, why
 ----------   ---     -----------------------------------------------------------
 2019/01/18 Autogen  Autogenerated version

=============================================================================*/
#include "icbuarb.h"
#include "icbuarbi.h"
#include "comdef.h"

/*============================================================================
                          DEFINES
============================================================================*/
/*============================================================================
                   INTERNAL DATA DECLARATIONS
============================================================================*/
/*============================================================================
                        MASTER DECLARATIONS
============================================================================*/
/* APPS_PROC */
static icb_master master_apps_proc =
{
  ICBID_MASTER_APPSS_PROC,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_BIMC_1 */
static icb_master master_pcnoc_bimc_1 =
{
  ICBID_MASTER_PCNOC_BIMC_1,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* CRYPTO_C0 */
static icb_master master_crypto_c0 =
{
  ICBID_MASTER_CRYPTO_CORE0,
  { 
    0
  },
  true, /* remote node? */
  650, /* width in bytes */
  0,
  NULL,
};

/* BLSP_1 */
static icb_master master_blsp_1 =
{
  ICBID_MASTER_BLSP_1,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* BIMC_PCNOC */
static icb_master master_bimc_pcnoc =
{
  ICBID_MASTER_BIMC_PCNOC,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* CR_VIRT_PCNOC */
static icb_master master_cr_virt_pcnoc =
{
  ICBID_MASTER_CRVIRT_PCNOC,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_INT_0 */
static icb_master master_pcnoc_int_0 =
{
  ICBID_MASTER_PCNOC_INT_0,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_INT_1 */
static icb_master master_pcnoc_int_1 =
{
  ICBID_MASTER_PCNOC_INT_1,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_INT_2 */
static icb_master master_pcnoc_int_2 =
{
  ICBID_MASTER_PCNOC_INT_2,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_INT_3 */
static icb_master master_pcnoc_int_3 =
{
  ICBID_MASTER_PCNOC_INT_3,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};


/*============================================================================
                        SLAVE DECLARATIONS
============================================================================*/
/* EBI */
static icb_slave slave_ebi =
{
  ICBID_SLAVE_EBI1,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* BIMC_PCNOC */
static icb_slave slave_bimc_pcnoc =
{
  ICBID_SLAVE_BIMC_PCNOC,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* BLSP_1 */
static icb_slave slave_blsp_1 =
{
  ICBID_SLAVE_BLSP_1,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* CRYPTO0_CFG */
static icb_slave slave_crypto0_cfg =
{
  ICBID_SLAVE_CRYPTO_0_CFG,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* PRNG */
static icb_slave slave_prng =
{
  ICBID_SLAVE_PRNG,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_BIMC_1 */
static icb_slave slave_pcnoc_bimc_1 =
{
  ICBID_SLAVE_PCNOC_BIMC_1,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* IMEM */
static icb_slave slave_imem =
{
  ICBID_SLAVE_IMEM,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_INT_0 */
static icb_slave slave_pcnoc_int_0 =
{
  ICBID_SLAVE_PCNOC_INT_0,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_INT_1 */
static icb_slave slave_pcnoc_int_1 =
{
  ICBID_SLAVE_PCNOC_INT_1,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_INT_2 */
static icb_slave slave_pcnoc_int_2 =
{
  ICBID_SLAVE_PCNOC_INT_2,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_INT_3 */
static icb_slave slave_pcnoc_int_3 =
{
  ICBID_SLAVE_PCNOC_INT_3,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/*============================================================================
                        TOPOLOGY ROUTE DECLARATIONS
============================================================================*/
static icb_pair route_apps_proc_blsp_1_hops[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_blsp_1
  },
};

static icb_route route_apps_proc_blsp_1 =
{

  ICBID_MASTER_APPSS_PROC,
  ICBID_SLAVE_BLSP_1,
  3,
  route_apps_proc_blsp_1_hops
};
 
static icb_pair route_apps_proc_crypto0_cfg_hops[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_crypto0_cfg
  },
};

static icb_route route_apps_proc_crypto0_cfg =
{

  ICBID_MASTER_APPSS_PROC,
  ICBID_SLAVE_CRYPTO_0_CFG,
  3,
  route_apps_proc_crypto0_cfg_hops
};
 
static icb_pair route_apps_proc_ebi_hops[1] =
{
  {
    &master_apps_proc,
    &slave_ebi
  },
};

static icb_route route_apps_proc_ebi =
{

  ICBID_MASTER_APPSS_PROC,
  ICBID_SLAVE_EBI1,
  1,
  route_apps_proc_ebi_hops
};
 
static icb_pair route_apps_proc_imem_hops[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_imem
  },
};

static icb_route route_apps_proc_imem =
{

  ICBID_MASTER_APPSS_PROC,
  ICBID_SLAVE_IMEM,
  3,
  route_apps_proc_imem_hops
};
 
static icb_pair route_apps_proc_prng_hops[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_prng
  },
};

static icb_route route_apps_proc_prng =
{

  ICBID_MASTER_APPSS_PROC,
  ICBID_SLAVE_PRNG,
  3,
  route_apps_proc_prng_hops
};
 
static icb_pair route_blsp_1_ebi_hops[4] =
{
  {
    &master_blsp_1,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_1
  },
  {
    &master_pcnoc_int_1,
    &slave_pcnoc_bimc_1
  },
  {
    &master_pcnoc_bimc_1,
    &slave_ebi
  },
};

static icb_route route_blsp_1_ebi =
{

  ICBID_MASTER_BLSP_1,
  ICBID_SLAVE_EBI1,
  4,
  route_blsp_1_ebi_hops
};
 
static icb_pair route_blsp_1_imem_hops[3] =
{
  {
    &master_blsp_1,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_imem
  },
};

static icb_route route_blsp_1_imem =
{

  ICBID_MASTER_BLSP_1,
  ICBID_SLAVE_IMEM,
  3,
  route_blsp_1_imem_hops
};
 
static icb_pair route_crypto_c0_ebi_hops[5] =
{
  {
    &master_crypto_c0,
    NULL
  },
  {
    &master_cr_virt_pcnoc,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_1
  },
  {
    &master_pcnoc_int_1,
    &slave_pcnoc_bimc_1
  },
  {
    &master_pcnoc_bimc_1,
    &slave_ebi
  },
};

static icb_route route_crypto_c0_ebi =
{

  ICBID_MASTER_CRYPTO_CORE0,
  ICBID_SLAVE_EBI1,
  5,
  route_crypto_c0_ebi_hops
};
 
static icb_pair route_crypto_c0_imem_hops[4] =
{
  {
    &master_crypto_c0,
    NULL
  },
  {
    &master_cr_virt_pcnoc,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_imem
  },
};

static icb_route route_crypto_c0_imem =
{

  ICBID_MASTER_CRYPTO_CORE0,
  ICBID_SLAVE_IMEM,
  4,
  route_crypto_c0_imem_hops
};
 
/*============================================================================
                   EXTERNAL DATA DECLARATIONS
============================================================================*/
static icb_route *icb_route_list[9] =
{
  &route_apps_proc_blsp_1,
  &route_apps_proc_crypto0_cfg,
  &route_apps_proc_ebi,
  &route_apps_proc_imem,
  &route_apps_proc_prng,
  &route_blsp_1_ebi,
  &route_blsp_1_imem,
  &route_crypto_c0_ebi,
  &route_crypto_c0_imem,
};

const icb_info info =
{
  9,
  icb_route_list,
  0,
  NULL,
};
