#ifndef QDSS_ETM_ARM_REGS_H
#define QDSS_ETM_ARM_REGS_H

/*=============================================================================

FILE:         qdss_etm_arm_regs.h

DESCRIPTION:  

================================================================================
              Copyright (c) 2013 Qualcomm Technologies Incorporated.
                         All Rights Reserved.
                QUALCOMM Proprietary and Confidential
==============================================================================*/
#include "HALhwio.h"

extern volatile uint32 QDSS_ETMARM_REG_BASE;


#define _bit(_n)  (1<<_n)


#define HWIO_QDSS_ETMARM_CR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x000)
#define HWIO_QDSS_ETMARM_CR_IN   in_dword(HWIO_QDSS_ETMARM_CR_ADDR)
#define HWIO_QDSS_ETMARM_CR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_CR_ADDR,v)


#define HWIO_QDSS_ETMARM_CR_PWRDN_SHFT  0
#define HWIO_QDSS_ETMARM_CR_PWRDN_BMSK  _bit(0)


#define HWIO_QDSS_ETMARM_CR_PROG_SHFT  10
#define HWIO_QDSS_ETMARM_CR_PROG_BMSK  _bit(10)


#define HWIO_QDSS_ETMARM_CCR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x004)
#define HWIO_QDSS_ETMARM_CCR_IN   in_dword(HWIO_QDSS_ETMARM_CCR_ADDR)
#define HWIO_QDSS_ETMARM_CCR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_CCR_ADDR,v)

#define HWIO_QDSS_ETMARM_TRIGGER_ADDR	  (QDSS_ETMARM_REG_BASE + 0x008)
#define HWIO_QDSS_ETMARM_TRIGGER_IN   in_dword(HWIO_QDSS_ETMARM_TRIGGER_ADDR)
#define HWIO_QDSS_ETMARM_TRIGGER_OUT(v)   out_dword(HWIO_QDSS_ETMARM_TRIGGER_ADDR,v)

#define HWIO_QDSS_ETMARM_ASSICCTLR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x00C)
#define HWIO_QDSS_ETMARM_ASSICCTLR_IN   in_dword(HWIO_QDSS_ETMARM_ASSICCTLR_ADDR)
#define HWIO_QDSS_ETMARM_ASSICCTLR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_ASSICCTLR_ADDR,v)

#define HWIO_QDSS_ETMARM_SR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x010)
#define HWIO_QDSS_ETMARM_SR_IN   in_dword(HWIO_QDSS_ETMARM_SR_ADDR)
#define HWIO_QDSS_ETMARM_SR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_SR_ADDR,v)

#define HWIO_QDSS_ETMARM_SCR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x014)
#define HWIO_QDSS_ETMARM_SCR_IN   in_dword(HWIO_QDSS_ETMARM_SCR_ADDR)
#define HWIO_QDSS_ETMARM_SCR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_SCR_ADDR,v)

#define HWIO_QDSS_ETMARM_TSSCR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x018)
#define HWIO_QDSS_ETMARM_TSSCR_IN   in_dword(HWIO_QDSS_ETMARM_TSSCR_ADDR)
#define HWIO_QDSS_ETMARM_TSSCR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_TSSCR_ADDR,v)

#define HWIO_QDSS_ETMARM_TECR2_ADDR	  (QDSS_ETMARM_REG_BASE + 0x01C)
#define HWIO_QDSS_ETMARM_TECR2_IN   in_dword(HWIO_QDSS_ETMARM_TECR2_ADDR)
#define HWIO_QDSS_ETMARM_TECR2_OUT(v)   out_dword(HWIO_QDSS_ETMARM_TECR2_ADDR,v)

#define HWIO_QDSS_ETMARM_TEEVR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x020)
#define HWIO_QDSS_ETMARM_TEEVR_IN   in_dword(HWIO_QDSS_ETMARM_TEEVR_ADDR)
#define HWIO_QDSS_ETMARM_TEEVR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_TEEVR_ADDR,v)

#define HWIO_QDSS_ETMARM_TECR1_ADDR	  (QDSS_ETMARM_REG_BASE + 0x024)
#define HWIO_QDSS_ETMARM_TECR1_IN   in_dword(HWIO_QDSS_ETMARM_TECR1_ADDR)
#define HWIO_QDSS_ETMARM_TECR1_OUT(v)   out_dword(HWIO_QDSS_ETMARM_TECR1_ADDR,v)

#define HWIO_QDSS_ETMARM_FFLR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x02C)
#define HWIO_QDSS_ETMARM_FFLR_IN   in_dword(HWIO_QDSS_ETMARM_FFLR_ADDR)
#define HWIO_QDSS_ETMARM_FFLR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_FFLR_ADDR,v)

#define HWIO_QDSS_ETMARM_VDEVR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x030)
#define HWIO_QDSS_ETMARM_VDEVR_IN   in_dword(HWIO_QDSS_ETMARM_VDEVR_ADDR)
#define HWIO_QDSS_ETMARM_VDEVR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_VDEVR_ADDR,v)

#define HWIO_QDSS_ETMARM_VDCR1_ADDR	  (QDSS_ETMARM_REG_BASE + 0x034)
#define HWIO_QDSS_ETMARM_VDCR1_IN   in_dword(HWIO_QDSS_ETMARM_VDCR1_ADDR)
#define HWIO_QDSS_ETMARM_VDCR1_OUT(v)   out_dword(HWIO_QDSS_ETMARM_VDCR1_ADDR,v)

#define HWIO_QDSS_ETMARM_VDCR3_ADDR	  (QDSS_ETMARM_REG_BASE + 0x03C)
#define HWIO_QDSS_ETMARM_VDCR3_IN   in_dword(HWIO_QDSS_ETMARM_VDCR3_ADDR)
#define HWIO_QDSS_ETMARM_VDCR3_OUT(v)   out_dword(HWIO_QDSS_ETMARM_VDCR3_ADDR,v)

#define HWIO_QDSS_ETMARM_SQ12EVR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x180)
#define HWIO_QDSS_ETMARM_SQ12EVR_IN   in_dword(HWIO_QDSS_ETMARM_SQ12EVR_ADDR)
#define HWIO_QDSS_ETMARM_SQ12EVR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_SQ12EVR_ADDR,v)

#define HWIO_QDSS_ETMARM_SQ21EVR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x184)
#define HWIO_QDSS_ETMARM_SQ21EVR_IN   in_dword(HWIO_QDSS_ETMARM_SQ21EVR_ADDR)
#define HWIO_QDSS_ETMARM_SQ21EVR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_SQ21EVR_ADDR,v)

#define HWIO_QDSS_ETMARM_SQ23EVR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x188)
#define HWIO_QDSS_ETMARM_SQ23EVR_IN   in_dword(HWIO_QDSS_ETMARM_SQ23EVR_ADDR)
#define HWIO_QDSS_ETMARM_SQ23EVR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_SQ23EVR_ADDR,v)

#define HWIO_QDSS_ETMARM_SQ31EVR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x18C)
#define HWIO_QDSS_ETMARM_SQ31EVR_IN   in_dword(HWIO_QDSS_ETMARM_SQ31EVR_ADDR)
#define HWIO_QDSS_ETMARM_SQ31EVR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_SQ31EVR_ADDR,v)

#define HWIO_QDSS_ETMARM_SQ32EVR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x190)
#define HWIO_QDSS_ETMARM_SQ32EVR_IN   in_dword(HWIO_QDSS_ETMARM_SQ32EVR_ADDR)
#define HWIO_QDSS_ETMARM_SQ32EVR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_SQ32EVR_ADDR,v)

#define HWIO_QDSS_ETMARM_SQ13EVR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x194)
#define HWIO_QDSS_ETMARM_SQ13EVR_IN   in_dword(HWIO_QDSS_ETMARM_SQ13EVR_ADDR)
#define HWIO_QDSS_ETMARM_SQ13EVR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_SQ13EVR_ADDR,v)

#define HWIO_QDSS_ETMARM_SQR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x19C)
#define HWIO_QDSS_ETMARM_SQR_IN   in_dword(HWIO_QDSS_ETMARM_SQR_ADDR)
#define HWIO_QDSS_ETMARM_SQR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_SQR_ADDR,v)

#define HWIO_QDSS_ETMARM_CIDCMR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1BC)
#define HWIO_QDSS_ETMARM_CIDCMR_IN   in_dword(HWIO_QDSS_ETMARM_CIDCMR_ADDR)
#define HWIO_QDSS_ETMARM_CIDCMR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_CIDCMR_ADDR,v)

#define HWIO_QDSS_ETMARM_IMPSPEC0_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1C0)
#define HWIO_QDSS_ETMARM_IMPSPEC0_IN   in_dword(HWIO_QDSS_ETMARM_IMPSPEC0_ADDR)
#define HWIO_QDSS_ETMARM_IMPSPEC0_OUT(v)   out_dword(HWIO_QDSS_ETMARM_IMPSPEC0_ADDR,v)

#define HWIO_QDSS_ETMARM_IMPSPEC1_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1C4)
#define HWIO_QDSS_ETMARM_IMPSPEC1_IN   in_dword(HWIO_QDSS_ETMARM_IMPSPEC1_ADDR)
#define HWIO_QDSS_ETMARM_IMPSPEC1_OUT(v)   out_dword(HWIO_QDSS_ETMARM_IMPSPEC1_ADDR,v)

#define HWIO_QDSS_ETMARM_IMPSPEC2_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1C8)
#define HWIO_QDSS_ETMARM_IMPSPEC2_IN   in_dword(HWIO_QDSS_ETMARM_IMPSPEC2_ADDR)
#define HWIO_QDSS_ETMARM_IMPSPEC2_OUT(v)   out_dword(HWIO_QDSS_ETMARM_IMPSPEC2_ADDR,v)

#define HWIO_QDSS_ETMARM_IMPSPEC3_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1CC)
#define HWIO_QDSS_ETMARM_IMPSPEC3_IN   in_dword(HWIO_QDSS_ETMARM_IMPSPEC3_ADDR)
#define HWIO_QDSS_ETMARM_IMPSPEC3_OUT(v)   out_dword(HWIO_QDSS_ETMARM_IMPSPEC3_ADDR,v)

#define HWIO_QDSS_ETMARM_IMPSPEC4_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1D0)
#define HWIO_QDSS_ETMARM_IMPSPEC4_IN   in_dword(HWIO_QDSS_ETMARM_IMPSPEC4_ADDR)
#define HWIO_QDSS_ETMARM_IMPSPEC4_OUT(v)   out_dword(HWIO_QDSS_ETMARM_IMPSPEC4_ADDR,v)

#define HWIO_QDSS_ETMARM_IMPSPEC5_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1D4)
#define HWIO_QDSS_ETMARM_IMPSPEC5_IN   in_dword(HWIO_QDSS_ETMARM_IMPSPEC5_ADDR)
#define HWIO_QDSS_ETMARM_IMPSPEC5_OUT(v)   out_dword(HWIO_QDSS_ETMARM_IMPSPEC5_ADDR,v)

#define HWIO_QDSS_ETMARM_IMPSPEC6_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1D8)
#define HWIO_QDSS_ETMARM_IMPSPEC6_IN   in_dword(HWIO_QDSS_ETMARM_IMPSPEC6_ADDR)
#define HWIO_QDSS_ETMARM_IMPSPEC6_OUT(v)   out_dword(HWIO_QDSS_ETMARM_IMPSPEC6_ADDR,v)

#define HWIO_QDSS_ETMARM_IMPSPEC7_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1DC)
#define HWIO_QDSS_ETMARM_IMPSPEC7_IN   in_dword(HWIO_QDSS_ETMARM_IMPSPEC7_ADDR)
#define HWIO_QDSS_ETMARM_IMPSPEC7_OUT(v)   out_dword(HWIO_QDSS_ETMARM_IMPSPEC7_ADDR,v)

#define HWIO_QDSS_ETMARM_SYNCFR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1E0)
#define HWIO_QDSS_ETMARM_SYNCFR_IN   in_dword(HWIO_QDSS_ETMARM_SYNCFR_ADDR)
#define HWIO_QDSS_ETMARM_SYNCFR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_SYNCFR_ADDR,v)

#define HWIO_QDSS_ETMARM_IDR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1E4)
#define HWIO_QDSS_ETMARM_IDR_IN   in_dword(HWIO_QDSS_ETMARM_IDR_ADDR)
#define HWIO_QDSS_ETMARM_IDR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_IDR_ADDR,v)

#define HWIO_QDSS_ETMARM_CCER_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1E8)
#define HWIO_QDSS_ETMARM_CCER_IN   in_dword(HWIO_QDSS_ETMARM_CCER_ADDR)
#define HWIO_QDSS_ETMARM_CCER_OUT(v)   out_dword(HWIO_QDSS_ETMARM_CCER_ADDR,v)

#define HWIO_QDSS_ETMARM_EXTINSELR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1EC)
#define HWIO_QDSS_ETMARM_EXTINSELR_IN   in_dword(HWIO_QDSS_ETMARM_EXTINSELR_ADDR)
#define HWIO_QDSS_ETMARM_EXTINSELR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_EXTINSELR_ADDR,v)

#define HWIO_QDSS_ETMARM_TESSEICR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1F0)
#define HWIO_QDSS_ETMARM_TESSEICR_IN   in_dword(HWIO_QDSS_ETMARM_TESSEICR_ADDR)
#define HWIO_QDSS_ETMARM_TESSEICR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_TESSEICR_ADDR,v)

#define HWIO_QDSS_ETMARM_EIBCR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1F4)
#define HWIO_QDSS_ETMARM_EIBCR_IN   in_dword(HWIO_QDSS_ETMARM_EIBCR_ADDR)
#define HWIO_QDSS_ETMARM_EIBCR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_EIBCR_ADDR,v)

#define HWIO_QDSS_ETMARM_TSEVR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1F8)
#define HWIO_QDSS_ETMARM_TSEVR_IN   in_dword(HWIO_QDSS_ETMARM_TSEVR_ADDR)
#define HWIO_QDSS_ETMARM_TSEVR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_TSEVR_ADDR,v)

#define HWIO_QDSS_ETMARM_AUXCR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x1FC)
#define HWIO_QDSS_ETMARM_AUXCR_IN   in_dword(HWIO_QDSS_ETMARM_AUXCR_ADDR)
#define HWIO_QDSS_ETMARM_AUXCR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_AUXCR_ADDR,v)

#define HWIO_QDSS_ETMARM_TRACEIDR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x200)
#define HWIO_QDSS_ETMARM_TRACEIDR_IN   in_dword(HWIO_QDSS_ETMARM_TRACEIDR_ADDR)
#define HWIO_QDSS_ETMARM_TRACEIDR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_TRACEIDR_ADDR,v)

#define HWIO_QDSS_ETMARM_IDR2_ADDR	  (QDSS_ETMARM_REG_BASE + 0x208)
#define HWIO_QDSS_ETMARM_IDR2_IN   in_dword(HWIO_QDSS_ETMARM_IDR2_ADDR)
#define HWIO_QDSS_ETMARM_IDR2_OUT(v)   out_dword(HWIO_QDSS_ETMARM_IDR2_ADDR,v)

#define HWIO_QDSS_ETMARM_VMIDCVR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x240)
#define HWIO_QDSS_ETMARM_VMIDCVR_IN   in_dword(HWIO_QDSS_ETMARM_VMIDCVR_ADDR)
#define HWIO_QDSS_ETMARM_VMIDCVR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_VMIDCVR_ADDR,v)

#define HWIO_QDSS_ETMARM_OSLAR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x300)
#define HWIO_QDSS_ETMARM_OSLAR_IN   in_dword(HWIO_QDSS_ETMARM_OSLAR_ADDR)
#define HWIO_QDSS_ETMARM_OSLAR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_OSLAR_ADDR,v)

#define HWIO_QDSS_ETMARM_OSLSR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x304)
#define HWIO_QDSS_ETMARM_OSLSR_IN   in_dword(HWIO_QDSS_ETMARM_OSLSR_ADDR)
#define HWIO_QDSS_ETMARM_OSLSR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_OSLSR_ADDR,v)

#define HWIO_QDSS_ETMARM_OSSRR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x308)
#define HWIO_QDSS_ETMARM_OSSRR_IN   in_dword(HWIO_QDSS_ETMARM_OSSRR_ADDR)
#define HWIO_QDSS_ETMARM_OSSRR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_OSSRR_ADDR,v)

#define HWIO_QDSS_ETMARM_PDCR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x310)
#define HWIO_QDSS_ETMARM_PDCR_IN   in_dword(HWIO_QDSS_ETMARM_PDCR_ADDR)
#define HWIO_QDSS_ETMARM_PDCR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_PDCR_ADDR,v)

#define HWIO_QDSS_ETMARM_PDSR_ADDR	  (QDSS_ETMARM_REG_BASE + 0x314)
#define HWIO_QDSS_ETMARM_PDSR_IN   in_dword(HWIO_QDSS_ETMARM_PDSR_ADDR)
#define HWIO_QDSS_ETMARM_PDSR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_PDSR_ADDR,v)

#define HWIO_QDSS_ETMARM_LAR_ADDR	  (QDSS_ETMARM_REG_BASE + 0xFB0)
#define HWIO_QDSS_ETMARM_LAR_IN   in_dword(HWIO_QDSS_ETMARM_LAR_ADDR)
#define HWIO_QDSS_ETMARM_LAR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_LAR_ADDR,v)

#define HWIO_QDSS_ETMARM_LSR_ADDR	  (QDSS_ETMARM_REG_BASE + 0xFB4)
#define HWIO_QDSS_ETMARM_LSR_IN   in_dword(HWIO_QDSS_ETMARM_LSR_ADDR)
#define HWIO_QDSS_ETMARM_LSR_OUT(v)   out_dword(HWIO_QDSS_ETMARM_LSR_ADDR,v)


#define HWIO_QDSS_ETMARM_ACVRn_ADDR(n)	  (QDSS_ETMARM_REG_BASE + (0x040 + (n * 4)))
#define HWIO_QDSS_ETMARM_ACTRn_ADDR(n)	  (QDSS_ETMARM_REG_BASE + (0x080 + (n * 4)))
#define HWIO_QDSS_ETMARM_DCVRn_ADDR(n)	  (QDSS_ETMARM_REG_BASE + (0x0C0 + (n * 8)))
#define HWIO_QDSS_ETMARM_DCMRn_ADDR(n)	  (QDSS_ETMARM_REG_BASE + (0x100 + (n * 8)))
#define HWIO_QDSS_ETMARM_CNTRLDVRn_ADDR(n)	  (QDSS_ETMARM_REG_BASE + (0x140 + (n * 4)))
#define HWIO_QDSS_ETMARM_CNTENRn_ADDR(n)	  (QDSS_ETMARM_REG_BASE + (0x150 + (n * 4)))
#define HWIO_QDSS_ETMARM_CNTRLDEVRn_ADDR(n)	  (QDSS_ETMARM_REG_BASE + (0x160 + (n * 4)))
#define HWIO_QDSS_ETMARM_CNTVRn_ADDR(n)	  (QDSS_ETMARM_REG_BASE + (0x170 + (n * 4)))
#define HWIO_QDSS_ETMARM_EXTOUTEVRn_ADDR(n)	  (QDSS_ETMARM_REG_BASE + (0x1A0 + (n * 4)))
#define HWIO_QDSS_ETMARM_CIDCVRn_ADDR(n)	  (QDSS_ETMARM_REG_BASE + (0x1B0 + (n * 4)))



#endif //QDSS_ETM_ARM_REGS_H
