/*===========================================================================

FILE:        ul_data.c

DESCRIPTION: This file implements the target-specific NPA Bus subnodes

   Copyright (c) 2016 QUALCOMM Technologies, Incorporated.
             All Rights Reserved
             QUALCOMM Proprietary/GTDR
-------------------------------------------------------------------------------

$Header: //components/rel/core.tx/6.0/systemdrivers/icb/src/9205/ul_data.c#1 $ 
$DateTime: 2020/01/30 22:49:35 $
$Author: pwbldsvc $
$Change: 22400605 $

                      EDIT HISTORY FOR FILE

 Autogenerated for target: Apps
 This file was generated using Autogen script: 
 gen.py

 when         who     what, where, why
 ----------   ---     -----------------------------------------------------------
 2016/06/27 Autogen  Autogenerated version

=============================================================================*/
#include "npa.h"
#include "npa_resource.h"
#include "npa_log.h"
#include "ul_i.h"
#include "ul_tree.h"
#include "icb_soc_data.h"

/*============================================================================
                          DEFINES
============================================================================*/
/*============================================================================
                   INTERNAL DATA DECLARATIONS
============================================================================*/
/*============================================================================
                        AXI CONFIG DECLARATIONS
============================================================================*/

/****************************************************************************/
/*                              BUSES                                       */
/****************************************************************************/
/**** Bus: bimc ****/
static HAL_bimc_InfoType bimc_hal_info =
{
  0, /* Base address */
  19200, /* QoS frequency */
};

static const char *bus_bimc_clk_names[1] =
{
  "/clk/bimc",
};

static npa_client_handle bus_bimc_clk_clients[1] = {0};

static icb_bus_def_type bimc_bus =
{
  "BIMC", /* HWIO base name */
  true, /* remote node? */ 
  0, /* base address */
  0x46000, /* HWIO region size */
  ICB_BUS_BIMC, /* Bus type */
  0, /* Address width */
  8, /* Data width */
  (void *)&bimc_hal_info, /* Bus info structure */
  1,    /* Config clock info */
  bus_bimc_clk_names,
  bus_bimc_clk_clients,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  {
    ICB_AGG_SCHEME_0,
    153,
    100,
  },
  0,    /* No power domains. */
  NULL,
  NULL,
};

/**** Bus: cr_virt ****/

static icb_bus_def_type cr_virt_bus =
{
  "", /* HWIO base name */
  true, /* remote node? */ 
  0, /* base address */
  0x0, /* HWIO region size */
  ICB_BUS_VIRT, /* Bus type */
  0, /* Address width */
  8, /* Data width */
  NULL, /* Bus info structure */
  0,    /* No config clocks. */
  NULL,
  NULL,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  {
    ICB_AGG_SCHEME_LEGACY,
    0,
    0,
  },
  0,    /* No power domains. */
  NULL,
  NULL,
};

/**** Bus: pcnoc ****/
static HAL_noc_QosMasterInfoType pcnoc_master_info[15] =
{
  {NOC_QOS_ALLOWED_MODE_BYPASS | NOC_QOS_ALLOWED_MODE_FIXED | NOC_QOS_ALLOWED_MODE_LIMITER | NOC_QOS_ALLOWED_MODE_REGULATOR}, /* cr_virt_pcnoc */
  {0}, /* unused port 1 */
  {0}, /* unused port 2 */
  {0}, /* unused port 3 */
  {0}, /* unused port 4 */
  {NOC_QOS_ALLOWED_MODE_BYPASS | NOC_QOS_ALLOWED_MODE_FIXED}, /* qpic */
  {NOC_QOS_ALLOWED_MODE_BYPASS | NOC_QOS_ALLOWED_MODE_FIXED}, /* blsp_1 */
  {0}, /* unused port 7 */
  {0}, /* unused port 8 */
  {0}, /* unused port 9 */
  {0}, /* unused port 10 */
  {0}, /* unused port 11 */
  {NOC_QOS_ALLOWED_MODE_BYPASS | NOC_QOS_ALLOWED_MODE_FIXED}, /* usb_hs1 */
  {NOC_QOS_ALLOWED_MODE_BYPASS | NOC_QOS_ALLOWED_MODE_FIXED}, /* qdss_bam */
  {NOC_QOS_ALLOWED_MODE_BYPASS | NOC_QOS_ALLOWED_MODE_FIXED}, /* qdss_etr */
};

static HAL_noc_InfoType pcnoc_hal_info =
{
  0,        /* Base address */
  13,     /* Number of masters */
  15, /* Number of masters with QoS */ 
  20,      /* Number of slaves */ 
  19200,         /* QoS frequency */ 
  pcnoc_master_info, /* QoS master info */
  false, /* Save/Restore unused here. */
  NULL,
  0,
  NULL,
  NOC_QOS_OFFSET_0x7_0x1, /* NOC layout type */
};

static const char *bus_pcnoc_clk_names[1] =
{
  "/clk/pcnoc",
};

static npa_client_handle bus_pcnoc_clk_clients[1] = {0};

static icb_bus_def_type pcnoc_bus =
{
  "PC_NOC", /* HWIO base name */
  true, /* remote node? */ 
  0, /* base address */
  0x17100, /* HWIO region size */
  ICB_BUS_NOC, /* Bus type */
  0, /* Address width */
  8, /* Data width */
  (void *)&pcnoc_hal_info, /* Bus info structure */
  1,    /* Config clock info */
  bus_pcnoc_clk_names,
  bus_pcnoc_clk_clients,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  {
    ICB_AGG_SCHEME_LEGACY,
    0,
    0,
  },
  0,    /* No power domains. */
  NULL,
  NULL,
};

/****************************************************************************/
/*                              SLAVES                                      */
/****************************************************************************/
/**** Slave: audio ****/
/* slave port ids */
static uint32_t cfg_slave_audio_ports[1] =
{
  14, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_audio =
{
  ICBID_SLAVE_AUDIO, /* slaveId */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_audio_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: bimc_pcnoc ****/
/* slave port ids */
static uint32_t cfg_slave_bimc_pcnoc_ports[1] =
{
  1, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_bimc_pcnoc =
{
  ICBID_SLAVE_BIMC_PCNOC, /* slaveId */
  &bimc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_bimc_pcnoc_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: blsp_1 ****/
/* slave port ids */
static uint32_t cfg_slave_blsp_1_ports[1] =
{
  0, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_blsp_1 =
{
  ICBID_SLAVE_BLSP_1, /* slaveId */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_blsp_1_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: cr_virt_pcnoc ****/
/* slave port ids */
static uint32_t cfg_slave_cr_virt_pcnoc_ports[1] =
{
  0, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_cr_virt_pcnoc =
{
  ICBID_SLAVE_CRVIRT_PCNOC, /* slaveId */
  &cr_virt_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_cr_virt_pcnoc_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: ebi ****/
/* slave port ids */
static uint32_t cfg_slave_ebi_ports[1] =
{
  0, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_ebi =
{
  ICBID_SLAVE_EBI1, /* slaveId */
  &bimc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_ebi_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: imem ****/
/* slave port ids */
static uint32_t cfg_slave_imem_ports[1] =
{
  43, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_imem =
{
  ICBID_SLAVE_IMEM, /* slaveId */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_imem_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: imem_cfg ****/
/* slave port ids */
static uint32_t cfg_slave_imem_cfg_ports[1] =
{
  34, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_imem_cfg =
{
  ICBID_SLAVE_IMEM_CFG, /* slaveId */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_imem_cfg_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: message_ram ****/
/* slave port ids */
static uint32_t cfg_slave_message_ram_ports[1] =
{
  9, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_message_ram =
{
  ICBID_SLAVE_MESSAGE_RAM, /* slaveId */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_message_ram_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: pcnoc_bimc_1 ****/
/* slave port ids */
static uint32_t cfg_slave_pcnoc_bimc_1_ports[1] =
{
  41, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_pcnoc_bimc_1 =
{
  ICBID_SLAVE_PCNOC_BIMC_1, /* slaveId */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_pcnoc_bimc_1_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: pcnoc_int_0 ****/
/* slave definition */
static icb_slave_def_type cfg_slave_pcnoc_int_0 =
{
  ICBID_SLAVE_PCNOC_INT_0, /* slaveId */
  &pcnoc_bus, /* pBus */
  0, /* Number of ports */
  NULL, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: pcnoc_int_1 ****/
/* slave definition */
static icb_slave_def_type cfg_slave_pcnoc_int_1 =
{
  ICBID_SLAVE_PCNOC_INT_1, /* slaveId */
  &pcnoc_bus, /* pBus */
  0, /* Number of ports */
  NULL, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: pcnoc_int_2 ****/
/* slave definition */
static icb_slave_def_type cfg_slave_pcnoc_int_2 =
{
  ICBID_SLAVE_PCNOC_INT_2, /* slaveId */
  &pcnoc_bus, /* pBus */
  0, /* Number of ports */
  NULL, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: pcnoc_int_3 ****/
/* slave definition */
static icb_slave_def_type cfg_slave_pcnoc_int_3 =
{
  ICBID_SLAVE_PCNOC_INT_3, /* slaveId */
  &pcnoc_bus, /* pBus */
  0, /* Number of ports */
  NULL, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: pcnoc_m_0 ****/
/* slave port ids */
static uint32_t cfg_slave_pcnoc_m_0_ports[1] =
{
  42, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_pcnoc_m_0 =
{
  ICBID_SLAVE_PCNOC_M_0, /* slaveId */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_pcnoc_m_0_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: pdm ****/
/* slave port ids */
static uint32_t cfg_slave_pdm_ports[1] =
{
  10, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_pdm =
{
  ICBID_SLAVE_PDM, /* slaveId */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_pdm_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: pmic_arb ****/
/* slave port ids */
static uint32_t cfg_slave_pmic_arb_ports[1] =
{
  39, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_pmic_arb =
{
  ICBID_SLAVE_PMIC_ARB, /* slaveId */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_pmic_arb_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: prng ****/
/* slave port ids */
static uint32_t cfg_slave_prng_ports[1] =
{
  11, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_prng =
{
  ICBID_SLAVE_PRNG, /* slaveId */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_prng_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qdss_cfg ****/
/* slave port ids */
static uint32_t cfg_slave_qdss_cfg_ports[1] =
{
  23, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qdss_cfg =
{
  ICBID_SLAVE_QDSS_CFG, /* slaveId */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qdss_cfg_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qdss_stm ****/
/* slave port ids */
static uint32_t cfg_slave_qdss_stm_ports[1] =
{
  45, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qdss_stm =
{
  ICBID_SLAVE_QDSS_STM, /* slaveId */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qdss_stm_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: tcsr ****/
/* slave port ids */
static uint32_t cfg_slave_tcsr_ports[1] =
{
  6, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_tcsr =
{
  ICBID_SLAVE_TCSR, /* slaveId */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_tcsr_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: tlmm ****/
/* slave port ids */
static uint32_t cfg_slave_tlmm_ports[1] =
{
  29, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_tlmm =
{
  ICBID_SLAVE_TLMM, /* slaveId */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_tlmm_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: usb_hs ****/
/* slave port ids */
static uint32_t cfg_slave_usb_hs_ports[1] =
{
  40, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_usb_hs =
{
  ICBID_SLAVE_USB_HS, /* slaveId */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_usb_hs_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: usb_phy ****/
/* slave port ids */
static uint32_t cfg_slave_usb_phy_ports[1] =
{
  13, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_usb_phy =
{
  ICBID_SLAVE_USB_PHY_CFG, /* slaveId */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_usb_phy_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/****************************************************************************/
/*                              MASTERS                                     */
/****************************************************************************/
/**** Master: apps_proc ****/
/* master port ids */
static uint32_t cfg_master_apps_proc_ports[1] =
{
  0, /* port 0 */
};

static uint32_t cfg_master_apps_proc_qos_ports[1] =
{
  0, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_apps_proc =
{
  ICBID_MASTER_APPSS_PROC, /* master id */
  &bimc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_apps_proc_ports, /* pPortIds */
  cfg_master_apps_proc_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  10000, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: audio ****/
/* master port ids */
static uint32_t cfg_master_audio_ports[1] =
{
  0, /* port 0 */
};

static uint32_t cfg_master_audio_halt_ports[1] =
{
  7, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_audio =
{
  ICBID_MASTER_AUDIO, /* master id */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_audio_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  cfg_master_audio_halt_ports, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: bimc_pcnoc ****/
/* master port ids */
static uint32_t cfg_master_bimc_pcnoc_ports[1] =
{
  10, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_bimc_pcnoc =
{
  ICBID_MASTER_BIMC_PCNOC, /* master id */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_bimc_pcnoc_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: blsp_1 ****/
/* master port ids */
static uint32_t cfg_master_blsp_1_ports[1] =
{
  4, /* port 0 */
};

static uint32_t cfg_master_blsp_1_qos_ports[1] =
{
  6, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_blsp_1 =
{
  ICBID_MASTER_BLSP_1, /* master id */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_blsp_1_ports, /* pPortIds */
  cfg_master_blsp_1_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: cr_virt_pcnoc ****/
/* master port ids */
static uint32_t cfg_master_cr_virt_pcnoc_ports[1] =
{
  11, /* port 0 */
};

static uint32_t cfg_master_cr_virt_pcnoc_qos_ports[1] =
{
  0, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_cr_virt_pcnoc =
{
  ICBID_MASTER_CRVIRT_PCNOC, /* master id */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_cr_virt_pcnoc_ports, /* pPortIds */
  cfg_master_cr_virt_pcnoc_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: crypto_c0 ****/
/* master port ids */
static uint32_t cfg_master_crypto_c0_ports[1] =
{
  0, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_crypto_c0 =
{
  ICBID_MASTER_CRYPTO_CORE0, /* master id */
  &cr_virt_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_crypto_c0_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: pcnoc_bimc_1 ****/
/* master port ids */
static uint32_t cfg_master_pcnoc_bimc_1_ports[1] =
{
  3, /* port 0 */
};

static uint32_t cfg_master_pcnoc_bimc_1_qos_ports[1] =
{
  3, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_pcnoc_bimc_1 =
{
  ICBID_MASTER_PCNOC_BIMC_1, /* master id */
  &bimc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_pcnoc_bimc_1_ports, /* pPortIds */
  cfg_master_pcnoc_bimc_1_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  10000, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: pcnoc_int_0 ****/
/* master definition */
static icb_master_def_type cfg_master_pcnoc_int_0 =
{
  ICBID_MASTER_PCNOC_INT_0, /* master id */
  &pcnoc_bus, /* pBus */
  0, /* Number of ports */
  NULL, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: pcnoc_int_1 ****/
/* master definition */
static icb_master_def_type cfg_master_pcnoc_int_1 =
{
  ICBID_MASTER_PCNOC_INT_1, /* master id */
  &pcnoc_bus, /* pBus */
  0, /* Number of ports */
  NULL, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: pcnoc_int_2 ****/
/* master definition */
static icb_master_def_type cfg_master_pcnoc_int_2 =
{
  ICBID_MASTER_PCNOC_INT_2, /* master id */
  &pcnoc_bus, /* pBus */
  0, /* Number of ports */
  NULL, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: pcnoc_int_3 ****/
/* master definition */
static icb_master_def_type cfg_master_pcnoc_int_3 =
{
  ICBID_MASTER_PCNOC_INT_3, /* master id */
  &pcnoc_bus, /* pBus */
  0, /* Number of ports */
  NULL, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: pcnoc_m_0 ****/
/* master port ids */
static uint32_t cfg_master_pcnoc_m_0_ports[1] =
  {
  42, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_pcnoc_m_0 =
{
  ICBID_MASTER_PCNOC_M_0, /* master id */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_pcnoc_m_0_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: qdss_bam ****/
/* master port ids */
static uint32_t cfg_master_qdss_bam_ports[1] =
{
  7, /* port 0 */
};

static uint32_t cfg_master_qdss_bam_qos_ports[1] =
{
  13, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_qdss_bam =
{
  ICBID_MASTER_QDSS_BAM, /* master id */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_qdss_bam_ports, /* pPortIds */
  cfg_master_qdss_bam_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: qdss_etr ****/
/* master port ids */
static uint32_t cfg_master_qdss_etr_ports[1] =
{
  13, /* port 0 */
};

static uint32_t cfg_master_qdss_etr_qos_ports[1] =
{
  14, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_qdss_etr =
{
  ICBID_MASTER_QDSS_ETR, /* master id */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_qdss_etr_ports, /* pPortIds */
  cfg_master_qdss_etr_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: qpic ****/
/* master port ids */
static uint32_t cfg_master_qpic_ports[1] =
{
  2, /* port 0 */
};

static uint32_t cfg_master_qpic_qos_ports[1] =
{
  5, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_qpic =
{
  ICBID_MASTER_QPIC, /* master id */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_qpic_ports, /* pPortIds */
  cfg_master_qpic_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: usb_hs1 ****/
/* master port ids */
static uint32_t cfg_master_usb_hs1_ports[1] =
{
  14, /* port 0 */
};

static uint32_t cfg_master_usb_hs1_qos_ports[1] =
{
  12, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_usb_hs1 =
{
  ICBID_MASTER_XM_USB_HS1, /* master id */
  &pcnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_usb_hs1_ports, /* pPortIds */
  cfg_master_usb_hs1_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/****************************************************************************/
/*                              LISTS                                       */
/****************************************************************************/
/* List of buses */
const uint32 u32cfg_bus_list_size   = 3;
icb_bus_def_type *cfg_bus_list[3] = 
{
  &bimc_bus,
  &cr_virt_bus,
  &pcnoc_bus,
};

/* List of slaves */
const uint32 u32cfg_slave_list_size   = 23;
icb_slave_def_type *cfg_slave_list[23] = 
{
  &cfg_slave_audio,
  &cfg_slave_bimc_pcnoc,
  &cfg_slave_blsp_1,
  &cfg_slave_cr_virt_pcnoc,
  &cfg_slave_ebi,
  &cfg_slave_imem,
  &cfg_slave_imem_cfg,
  &cfg_slave_message_ram,
  &cfg_slave_pcnoc_bimc_1,
  &cfg_slave_pcnoc_int_0,
  &cfg_slave_pcnoc_int_1,
  &cfg_slave_pcnoc_int_2,
  &cfg_slave_pcnoc_int_3,
  &cfg_slave_pcnoc_m_0,
  &cfg_slave_pdm,
  &cfg_slave_pmic_arb,
  &cfg_slave_prng,
  &cfg_slave_qdss_cfg,
  &cfg_slave_qdss_stm,
  &cfg_slave_tcsr,
  &cfg_slave_tlmm,
  &cfg_slave_usb_hs,
  &cfg_slave_usb_phy,
};

/* List of masters */
const uint32 u32cfg_master_list_size   = 16;
icb_master_def_type *cfg_master_list[16] = 
{
  &cfg_master_apps_proc,
  &cfg_master_audio,
  &cfg_master_bimc_pcnoc,
  &cfg_master_blsp_1,
  &cfg_master_cr_virt_pcnoc,
  &cfg_master_crypto_c0,
  &cfg_master_pcnoc_bimc_1,
  &cfg_master_pcnoc_int_0,
  &cfg_master_pcnoc_int_1,
  &cfg_master_pcnoc_int_2,
  &cfg_master_pcnoc_int_3,
  &cfg_master_pcnoc_m_0,
  &cfg_master_qdss_bam,
  &cfg_master_qdss_etr,
  &cfg_master_qpic,
  &cfg_master_usb_hs1,
};

/* List of configuration clocks */
const uint32 u32ul_cfg_clk_node_list_size   = 2;
const char *ul_cfg_clock_node_list[] =
{
  "/clk/bimc",
  "/clk/pcnoc",
};

/* TCSR definitions for port halting */
HAL_tcsr_InfoType *cfg_tcsr_info = NULL;

/*============================================================================
                        TOPOLOGY ROUTE DECLARATIONS
============================================================================*/

/*****************************************************/
/*                       bimc                                      */
/*****************************************************/
/* Masters */
/* APPS_PROC */
static ul_clock_type master_apps_proc_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_apps_proc =
{
  /* Master Data */
  "/icb/master/apps_proc",
  ICBID_MASTER_APPSS_PROC,                  /* External Master ID */
  8,
  1,
  master_apps_proc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_apps_proc,
    NULL,
  },
  &cfg_master_apps_proc,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_apps_proc,
    NULL,
  },
};

/* PCNOC_BIMC_1 */
static ul_clock_type master_pcnoc_bimc_1_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_pcnoc_bimc_1 =
{
  /* Master Data */
  "/icb/master/pcnoc_bimc_1",
  ICBID_MASTER_PCNOC_BIMC_1,                /* External Master ID */
  8,
  1,
  master_pcnoc_bimc_1_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_pcnoc_bimc_1,
    NULL,
  },
  &cfg_master_pcnoc_bimc_1,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_pcnoc_bimc_1,
    NULL,
  },
};

/* Slaves */
/* EBI */
static ul_clock_type slave_ebi_slv_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_ebi =
{
  /* Slave Data */
  "/icb/slave/ebi",
  ICBID_SLAVE_EBI1,                        /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_ebi_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_ebi,
    NULL,
  },
  &cfg_slave_ebi
};

/* BIMC_PCNOC */
static ul_clock_type slave_bimc_pcnoc_slv_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_bimc_pcnoc =
{
  /* Slave Data */
  "/icb/slave/bimc_pcnoc",
  ICBID_SLAVE_BIMC_PCNOC,                  /* External Slave ID */
  8,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_bimc_pcnoc_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_bimc_pcnoc,
    NULL,
  },
  &cfg_slave_bimc_pcnoc
};

/*****************************************************/
/*                       cr_virt                                      */
/*****************************************************/
/* Masters */
/* CRYPTO_C0 */
static ul_master_data_type  master_crypto_c0 =
{
  /* Master Data */
  "/icb/master/crypto_c0",
  ICBID_MASTER_CRYPTO_CORE0,                /* External Master ID */
  650 | ICB_WIDTH_TYPE_RAW,
    0,
    NULL,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_crypto_c0,
    NULL,
  },
  &cfg_master_crypto_c0,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_crypto_c0,
    NULL,
  },
};

/* Slaves */
/* CR_VIRT_PCNOC */

static ul_slave_data_type  slave_cr_virt_pcnoc =
{
  /* Slave Data */
  "/icb/slave/cr_virt_pcnoc",
  ICBID_SLAVE_CRVIRT_PCNOC,                /* External Slave ID */
  8,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  0,
    NULL,
    0,
    NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_cr_virt_pcnoc,
    NULL,
  },
  &cfg_slave_cr_virt_pcnoc
};

/*****************************************************/
/*                       pcnoc                                      */
/*****************************************************/
/* Masters */
/* AUDIO */
static ul_clock_type master_audio_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_audio =
{
  /* Master Data */
  "/icb/master/audio",
  ICBID_MASTER_AUDIO,                       /* External Master ID */
  4,
  1,
  master_audio_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_audio,
    NULL,
  },
  &cfg_master_audio,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_audio,
    NULL,
  },
};

/* QPIC */
static ul_clock_type master_qpic_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_qpic =
{
  /* Master Data */
  "/icb/master/qpic",
  ICBID_MASTER_QPIC,                        /* External Master ID */
  4,
  1,
  master_qpic_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_qpic,
    NULL,
  },
  &cfg_master_qpic,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_qpic,
    NULL,
  },
};

/* BLSP_1 */
static ul_clock_type master_blsp_1_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_blsp_1 =
{
  /* Master Data */
  "/icb/master/blsp_1",
  ICBID_MASTER_BLSP_1,                      /* External Master ID */
  4,
  1,
  master_blsp_1_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_blsp_1,
    NULL,
  },
  &cfg_master_blsp_1,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_blsp_1,
    NULL,
  },
};

/* QDSS_BAM */
static ul_clock_type master_qdss_bam_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_qdss_bam =
{
  /* Master Data */
  "/icb/master/qdss_bam",
  ICBID_MASTER_QDSS_BAM,                    /* External Master ID */
  4,
  1,
  master_qdss_bam_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_qdss_bam,
    NULL,
  },
  &cfg_master_qdss_bam,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_qdss_bam,
    NULL,
  },
};

/* BIMC_PCNOC */
static ul_clock_type master_bimc_pcnoc_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_bimc_pcnoc =
{
  /* Master Data */
  "/icb/master/bimc_pcnoc",
  ICBID_MASTER_BIMC_PCNOC,                  /* External Master ID */
  8,
  1,
  master_bimc_pcnoc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_bimc_pcnoc,
    NULL,
  },
  &cfg_master_bimc_pcnoc,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_bimc_pcnoc,
    NULL,
  },
};

/* CR_VIRT_PCNOC */
static ul_clock_type master_cr_virt_pcnoc_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_cr_virt_pcnoc =
{
  /* Master Data */
  "/icb/master/cr_virt_pcnoc",
  ICBID_MASTER_CRVIRT_PCNOC,                /* External Master ID */
  8,
  1,
  master_cr_virt_pcnoc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_cr_virt_pcnoc,
    NULL,
  },
  &cfg_master_cr_virt_pcnoc,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_cr_virt_pcnoc,
    NULL,
  },
};

/* QDSS_ETR */
static ul_clock_type master_qdss_etr_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_qdss_etr =
{
  /* Master Data */
  "/icb/master/qdss_etr",
  ICBID_MASTER_QDSS_ETR,                    /* External Master ID */
  8,
  1,
  master_qdss_etr_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_qdss_etr,
    NULL,
  },
  &cfg_master_qdss_etr,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_qdss_etr,
    NULL,
  },
};

/* USB_HS1 */
static ul_clock_type master_usb_hs1_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_usb_hs1 =
{
  /* Master Data */
  "/icb/master/usb_hs1",
  ICBID_MASTER_XM_USB_HS1,                  /* External Master ID */
  8,
  1,
  master_usb_hs1_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_usb_hs1,
    NULL,
  },
  &cfg_master_usb_hs1,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_usb_hs1,
    NULL,
  },
};

/* PCNOC_M_0 */
static ul_clock_type master_pcnoc_m_0_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_pcnoc_m_0 =
{
  /* Master Data */
  "/icb/master/pcnoc_m_0",
  ICBID_MASTER_PCNOC_M_0,                   /* External Master ID */
  4,
  1,
  master_pcnoc_m_0_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_pcnoc_m_0,
    NULL,
  },
  &cfg_master_pcnoc_m_0,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_pcnoc_m_0,
    NULL,
  },
};

/* PCNOC_INT_0 */
static ul_clock_type master_pcnoc_int_0_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_pcnoc_int_0 =
{
  /* Master Data */
  "/icb/master/pcnoc_int_0",
  ICBID_MASTER_PCNOC_INT_0,                 /* External Master ID */
  4,
  1,
  master_pcnoc_int_0_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_pcnoc_int_0,
    NULL,
  },
  &cfg_master_pcnoc_int_0,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_pcnoc_int_0,
    NULL,
  },
};

/* PCNOC_INT_1 */
static ul_clock_type master_pcnoc_int_1_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_pcnoc_int_1 =
{
  /* Master Data */
  "/icb/master/pcnoc_int_1",
  ICBID_MASTER_PCNOC_INT_1,                 /* External Master ID */
  4,
  1,
  master_pcnoc_int_1_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_pcnoc_int_1,
    NULL,
  },
  &cfg_master_pcnoc_int_1,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_pcnoc_int_1,
    NULL,
  },
};

/* PCNOC_INT_2 */
static ul_clock_type master_pcnoc_int_2_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_pcnoc_int_2 =
{
  /* Master Data */
  "/icb/master/pcnoc_int_2",
  ICBID_MASTER_PCNOC_INT_2,                 /* External Master ID */
  4,
  1,
  master_pcnoc_int_2_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_pcnoc_int_2,
    NULL,
  },
  &cfg_master_pcnoc_int_2,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_pcnoc_int_2,
    NULL,
  },
};

/* PCNOC_INT_3 */
static ul_clock_type master_pcnoc_int_3_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_pcnoc_int_3 =
{
  /* Master Data */
  "/icb/master/pcnoc_int_3",
  ICBID_MASTER_PCNOC_INT_3,                 /* External Master ID */
  4,
  1,
  master_pcnoc_int_3_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_pcnoc_int_3,
    NULL,
  },
  &cfg_master_pcnoc_int_3,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_pcnoc_int_3,
    NULL,
  },
};

/* Slaves */
/* BLSP_1 */
static ul_clock_type slave_blsp_1_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_blsp_1 =
{
  /* Slave Data */
  "/icb/slave/blsp_1",
  ICBID_SLAVE_BLSP_1,                      /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_blsp_1_slv_clks,
    0,
    NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_blsp_1,
    NULL,
  },
  &cfg_slave_blsp_1
};

/* TCSR */
static ul_clock_type slave_tcsr_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_tcsr =
{
  /* Slave Data */
  "/icb/slave/tcsr",
  ICBID_SLAVE_TCSR,                        /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_tcsr_slv_clks,
    0,
    NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_tcsr,
    NULL,
  },
  &cfg_slave_tcsr
};

/* MESSAGE_RAM */
static ul_clock_type slave_message_ram_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_message_ram =
{
  /* Slave Data */
  "/icb/slave/message_ram",
  ICBID_SLAVE_MESSAGE_RAM,                 /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_message_ram_slv_clks,
    0,
    NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_message_ram,
    NULL,
  },
  &cfg_slave_message_ram
};

/* PDM */
static ul_clock_type slave_pdm_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_pdm =
{
  /* Slave Data */
  "/icb/slave/pdm",
  ICBID_SLAVE_PDM,                         /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_pdm_slv_clks,
    0,
    NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_pdm,
    NULL,
  },
  &cfg_slave_pdm
};

/* PRNG */
static ul_clock_type slave_prng_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_prng =
{
  /* Slave Data */
  "/icb/slave/prng",
  ICBID_SLAVE_PRNG,                        /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_prng_slv_clks,
    0,
    NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_prng,
    NULL,
  },
  &cfg_slave_prng
};

/* USB_PHY */
static ul_clock_type slave_usb_phy_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_usb_phy =
{
  /* Slave Data */
  "/icb/slave/usb_phy",
  ICBID_SLAVE_USB_PHY_CFG,                 /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_usb_phy_slv_clks,
    0,
    NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_usb_phy,
    NULL,
  },
  &cfg_slave_usb_phy
};

/* AUDIO */
static ul_clock_type slave_audio_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_audio =
{
  /* Slave Data */
  "/icb/slave/audio",
  ICBID_SLAVE_AUDIO,                       /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_audio_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_audio,
    NULL,
  },
  &cfg_slave_audio
};

/* QDSS_CFG */
static ul_clock_type slave_qdss_cfg_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qdss_cfg =
{
  /* Slave Data */
  "/icb/slave/qdss_cfg",
  ICBID_SLAVE_QDSS_CFG,                    /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qdss_cfg_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qdss_cfg,
    NULL,
  },
  &cfg_slave_qdss_cfg
};

/* TLMM */
static ul_clock_type slave_tlmm_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_tlmm =
{
  /* Slave Data */
  "/icb/slave/tlmm",
  ICBID_SLAVE_TLMM,                        /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_tlmm_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_tlmm,
    NULL,
  },
  &cfg_slave_tlmm
};

/* IMEM_CFG */
static ul_clock_type slave_imem_cfg_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_imem_cfg =
{
  /* Slave Data */
  "/icb/slave/imem_cfg",
  ICBID_SLAVE_IMEM_CFG,                    /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_imem_cfg_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_imem_cfg,
    NULL,
  },
  &cfg_slave_imem_cfg
};

/* PMIC_ARB */
static ul_clock_type slave_pmic_arb_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_pmic_arb =
{
  /* Slave Data */
  "/icb/slave/pmic_arb",
  ICBID_SLAVE_PMIC_ARB,                    /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_pmic_arb_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_pmic_arb,
    NULL,
  },
  &cfg_slave_pmic_arb
};

/* USB_HS */
static ul_clock_type slave_usb_hs_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_usb_hs =
{
  /* Slave Data */
  "/icb/slave/usb_hs",
  ICBID_SLAVE_USB_HS,                      /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_usb_hs_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_usb_hs,
    NULL,
  },
  &cfg_slave_usb_hs
};

/* PCNOC_BIMC_1 */
static ul_clock_type slave_pcnoc_bimc_1_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_pcnoc_bimc_1 =
{
  /* Slave Data */
  "/icb/slave/pcnoc_bimc_1",
  ICBID_SLAVE_PCNOC_BIMC_1,                /* External Slave ID */
  8,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_pcnoc_bimc_1_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_pcnoc_bimc_1,
    NULL,
  },
  &cfg_slave_pcnoc_bimc_1
};

/* IMEM */
static ul_clock_type slave_imem_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_imem =
{
  /* Slave Data */
  "/icb/slave/imem",
  ICBID_SLAVE_IMEM,                        /* External Slave ID */
  8,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_imem_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_imem,
    NULL,
  },
  &cfg_slave_imem
};

/* QDSS_STM */
static ul_clock_type slave_qdss_stm_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qdss_stm =
{
  /* Slave Data */
  "/icb/slave/qdss_stm",
  ICBID_SLAVE_QDSS_STM,                    /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qdss_stm_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qdss_stm,
    NULL,
  },
  &cfg_slave_qdss_stm
};

/* PCNOC_M_0 */
static ul_clock_type slave_pcnoc_m_0_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_pcnoc_m_0 =
{
  /* Slave Data */
  "/icb/slave/pcnoc_m_0",
  ICBID_SLAVE_PCNOC_M_0,                   /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_pcnoc_m_0_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_pcnoc_m_0,
    NULL,
  },
  &cfg_slave_pcnoc_m_0
};

/* PCNOC_INT_0 */
static ul_clock_type slave_pcnoc_int_0_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_pcnoc_int_0 =
{
  /* Slave Data */
  "/icb/slave/pcnoc_int_0",
  ICBID_SLAVE_PCNOC_INT_0,                 /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_pcnoc_int_0_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_pcnoc_int_0,
    NULL,
  },
  &cfg_slave_pcnoc_int_0
};

/* PCNOC_INT_1 */
static ul_clock_type slave_pcnoc_int_1_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_pcnoc_int_1 =
{
  /* Slave Data */
  "/icb/slave/pcnoc_int_1",
  ICBID_SLAVE_PCNOC_INT_1,                 /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_pcnoc_int_1_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_pcnoc_int_1,
    NULL,
  },
  &cfg_slave_pcnoc_int_1
};

/* PCNOC_INT_2 */
static ul_clock_type slave_pcnoc_int_2_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_pcnoc_int_2 =
{
  /* Slave Data */
  "/icb/slave/pcnoc_int_2",
  ICBID_SLAVE_PCNOC_INT_2,                 /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_pcnoc_int_2_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_pcnoc_int_2,
    NULL,
  },
  &cfg_slave_pcnoc_int_2
};

/* PCNOC_INT_3 */
static ul_clock_type slave_pcnoc_int_3_slv_clks[1] =
{
  {
    "/clk/pcnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_pcnoc_int_3 =
{
  /* Slave Data */
  "/icb/slave/pcnoc_int_3",
  ICBID_SLAVE_PCNOC_INT_3,                 /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_pcnoc_int_3_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_pcnoc_int_3,
    NULL,
  },
  &cfg_slave_pcnoc_int_3
};

/* Define the valid routes  */
static ul_pair_type route_apps_proc_audio_list_array[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_audio
  },
};
static ul_route_list_type route_apps_proc_audio_list =
{
  3,
  route_apps_proc_audio_list_array
};
static ul_pair_type route_apps_proc_blsp_1_list_array[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_blsp_1
  },
};
static ul_route_list_type route_apps_proc_blsp_1_list =
{
  3,
  route_apps_proc_blsp_1_list_array
};
static ul_pair_type route_apps_proc_ebi_list_array[1] =
{
  {
    &master_apps_proc,
    &slave_ebi
  },
};
static ul_route_list_type route_apps_proc_ebi_list =
{
  1,
  route_apps_proc_ebi_list_array
};
static ul_pair_type route_apps_proc_imem_list_array[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_imem
  },
};
static ul_route_list_type route_apps_proc_imem_list =
{
  3,
  route_apps_proc_imem_list_array
};
static ul_pair_type route_apps_proc_imem_cfg_list_array[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_imem_cfg
  },
};
static ul_route_list_type route_apps_proc_imem_cfg_list =
{
  3,
  route_apps_proc_imem_cfg_list_array
};
static ul_pair_type route_apps_proc_message_ram_list_array[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_message_ram
  },
};
static ul_route_list_type route_apps_proc_message_ram_list =
{
  3,
  route_apps_proc_message_ram_list_array
};
static ul_pair_type route_apps_proc_pdm_list_array[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_pdm
  },
};
static ul_route_list_type route_apps_proc_pdm_list =
{
  3,
  route_apps_proc_pdm_list_array
};
static ul_pair_type route_apps_proc_pmic_arb_list_array[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_pmic_arb
  },
};
static ul_route_list_type route_apps_proc_pmic_arb_list =
{
  3,
  route_apps_proc_pmic_arb_list_array
};
static ul_pair_type route_apps_proc_prng_list_array[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_prng
  },
};
static ul_route_list_type route_apps_proc_prng_list =
{
  3,
  route_apps_proc_prng_list_array
};
static ul_pair_type route_apps_proc_qdss_cfg_list_array[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_qdss_cfg
  },
};
static ul_route_list_type route_apps_proc_qdss_cfg_list =
{
  3,
  route_apps_proc_qdss_cfg_list_array
};
static ul_pair_type route_apps_proc_qdss_stm_list_array[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_qdss_stm
  },
};
static ul_route_list_type route_apps_proc_qdss_stm_list =
{
  3,
  route_apps_proc_qdss_stm_list_array
};
static ul_pair_type route_apps_proc_tcsr_list_array[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_tcsr
  },
};
static ul_route_list_type route_apps_proc_tcsr_list =
{
  3,
  route_apps_proc_tcsr_list_array
};
static ul_pair_type route_apps_proc_tlmm_list_array[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_tlmm
  },
};
static ul_route_list_type route_apps_proc_tlmm_list =
{
  3,
  route_apps_proc_tlmm_list_array
};
static ul_pair_type route_apps_proc_usb_hs_list_array[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_usb_hs
  },
};
static ul_route_list_type route_apps_proc_usb_hs_list =
{
  3,
  route_apps_proc_usb_hs_list_array
};
static ul_pair_type route_apps_proc_usb_phy_list_array[3] =
{
  {
    &master_apps_proc,
    &slave_bimc_pcnoc
  },
  {
    &master_bimc_pcnoc,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_usb_phy
  },
};
static ul_route_list_type route_apps_proc_usb_phy_list =
{
  3,
  route_apps_proc_usb_phy_list_array
};
static ul_pair_type route_audio_ebi_list_array[5] =
{
  {
    &master_audio,
    &slave_pcnoc_m_0
  },
  {
    &master_pcnoc_m_0,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_1
  },
  {
    &master_pcnoc_int_1,
    &slave_pcnoc_bimc_1
  },
  {
    &master_pcnoc_bimc_1,
    &slave_ebi
  },
};
static ul_route_list_type route_audio_ebi_list =
{
  5,
  route_audio_ebi_list_array
};
static ul_pair_type route_audio_imem_list_array[4] =
{
  {
    &master_audio,
    &slave_pcnoc_m_0
  },
  {
    &master_pcnoc_m_0,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_imem
  },
};
static ul_route_list_type route_audio_imem_list =
{
  4,
  route_audio_imem_list_array
};
static ul_pair_type route_audio_qdss_stm_list_array[4] =
{
  {
    &master_audio,
    &slave_pcnoc_m_0
  },
  {
    &master_pcnoc_m_0,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_qdss_stm
  },
};
static ul_route_list_type route_audio_qdss_stm_list =
{
  4,
  route_audio_qdss_stm_list_array
};
static ul_pair_type route_blsp_1_ebi_list_array[4] =
{
  {
    &master_blsp_1,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_1
  },
  {
    &master_pcnoc_int_1,
    &slave_pcnoc_bimc_1
  },
  {
    &master_pcnoc_bimc_1,
    &slave_ebi
  },
};
static ul_route_list_type route_blsp_1_ebi_list =
{
  4,
  route_blsp_1_ebi_list_array
};
static ul_pair_type route_blsp_1_imem_list_array[3] =
{
  {
    &master_blsp_1,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_imem
  },
};
static ul_route_list_type route_blsp_1_imem_list =
{
  3,
  route_blsp_1_imem_list_array
};
static ul_pair_type route_blsp_1_qdss_stm_list_array[3] =
{
  {
    &master_blsp_1,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_qdss_stm
  },
};
static ul_route_list_type route_blsp_1_qdss_stm_list =
{
  3,
  route_blsp_1_qdss_stm_list_array
};
static ul_pair_type route_crypto_c0_ebi_list_array[5] =
{
  {
    &master_crypto_c0,
    &slave_cr_virt_pcnoc
  },
  {
    &master_cr_virt_pcnoc,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_1
  },
  {
    &master_pcnoc_int_1,
    &slave_pcnoc_bimc_1
  },
  {
    &master_pcnoc_bimc_1,
    &slave_ebi
  },
};
static ul_route_list_type route_crypto_c0_ebi_list =
{
  5,
  route_crypto_c0_ebi_list_array
};
static ul_pair_type route_crypto_c0_imem_list_array[4] =
{
  {
    &master_crypto_c0,
    &slave_cr_virt_pcnoc
  },
  {
    &master_cr_virt_pcnoc,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_imem
  },
};
static ul_route_list_type route_crypto_c0_imem_list =
{
  4,
  route_crypto_c0_imem_list_array
};
static ul_pair_type route_qdss_bam_ebi_list_array[3] =
{
  {
    &master_qdss_bam,
    &slave_pcnoc_int_1
  },
  {
    &master_pcnoc_int_1,
    &slave_pcnoc_bimc_1
  },
  {
    &master_pcnoc_bimc_1,
    &slave_ebi
  },
};
static ul_route_list_type route_qdss_bam_ebi_list =
{
  3,
  route_qdss_bam_ebi_list_array
};
static ul_pair_type route_qdss_bam_imem_list_array[2] =
{
  {
    &master_qdss_bam,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_imem
  },
};
static ul_route_list_type route_qdss_bam_imem_list =
{
  2,
  route_qdss_bam_imem_list_array
};
static ul_pair_type route_qdss_bam_usb_hs_list_array[2] =
{
  {
    &master_qdss_bam,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_usb_hs
  },
};
static ul_route_list_type route_qdss_bam_usb_hs_list =
{
  2,
  route_qdss_bam_usb_hs_list_array
};
static ul_pair_type route_qdss_etr_ebi_list_array[3] =
{
  {
    &master_qdss_etr,
    &slave_pcnoc_int_1
  },
  {
    &master_pcnoc_int_1,
    &slave_pcnoc_bimc_1
  },
  {
    &master_pcnoc_bimc_1,
    &slave_ebi
  },
};
static ul_route_list_type route_qdss_etr_ebi_list =
{
  3,
  route_qdss_etr_ebi_list_array
};
static ul_pair_type route_qdss_etr_imem_list_array[2] =
{
  {
    &master_qdss_etr,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_imem
  },
};
static ul_route_list_type route_qdss_etr_imem_list =
{
  2,
  route_qdss_etr_imem_list_array
};
static ul_pair_type route_qdss_etr_usb_hs_list_array[2] =
{
  {
    &master_qdss_etr,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_usb_hs
  },
};
static ul_route_list_type route_qdss_etr_usb_hs_list =
{
  2,
  route_qdss_etr_usb_hs_list_array
};
static ul_pair_type route_qpic_ebi_list_array[5] =
{
  {
    &master_qpic,
    &slave_pcnoc_m_0
  },
  {
    &master_pcnoc_m_0,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_1
  },
  {
    &master_pcnoc_int_1,
    &slave_pcnoc_bimc_1
  },
  {
    &master_pcnoc_bimc_1,
    &slave_ebi
  },
};
static ul_route_list_type route_qpic_ebi_list =
{
  5,
  route_qpic_ebi_list_array
};
static ul_pair_type route_qpic_imem_list_array[4] =
{
  {
    &master_qpic,
    &slave_pcnoc_m_0
  },
  {
    &master_pcnoc_m_0,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_imem
  },
};
static ul_route_list_type route_qpic_imem_list =
{
  4,
  route_qpic_imem_list_array
};
static ul_pair_type route_qpic_qdss_stm_list_array[4] =
{
  {
    &master_qpic,
    &slave_pcnoc_m_0
  },
  {
    &master_pcnoc_m_0,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_qdss_stm
  },
};
static ul_route_list_type route_qpic_qdss_stm_list =
{
  4,
  route_qpic_qdss_stm_list_array
};
static ul_pair_type route_usb_hs1_ebi_list_array[4] =
{
  {
    &master_usb_hs1,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_1
  },
  {
    &master_pcnoc_int_1,
    &slave_pcnoc_bimc_1
  },
  {
    &master_pcnoc_bimc_1,
    &slave_ebi
  },
};
static ul_route_list_type route_usb_hs1_ebi_list =
{
  4,
  route_usb_hs1_ebi_list_array
};
static ul_pair_type route_usb_hs1_imem_list_array[3] =
{
  {
    &master_usb_hs1,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_imem
  },
};
static ul_route_list_type route_usb_hs1_imem_list =
{
  3,
  route_usb_hs1_imem_list_array
};
static ul_pair_type route_usb_hs1_qdss_cfg_list_array[5] =
{
  {
    &master_usb_hs1,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_qdss_cfg
  },
{
    &master_usb_hs1,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_0
  },
  {
    &master_pcnoc_int_0,
    &slave_qdss_cfg
  },
};
static ul_route_list_type route_usb_hs1_qdss_cfg_list =
{
  5,
  route_usb_hs1_qdss_cfg_list_array
};
static ul_pair_type route_usb_hs1_qdss_stm_list_array[3] =
{
  {
    &master_usb_hs1,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_qdss_stm
  },
};
static ul_route_list_type route_usb_hs1_qdss_stm_list =
{
  3,
  route_usb_hs1_qdss_stm_list_array
};

/*============================================================================
                         ROUTE TREE - 36 routes
============================================================================*/
/* Forward declarations */
static ul_treeNodeType route_0x0L_apps_proc_ebi_node;
static ul_treeNodeType route_0x1aL_apps_proc_imem_node;
static ul_treeNodeType route_0x1eL_apps_proc_qdss_stm_node;
static ul_treeNodeType route_0x27L_apps_proc_blsp_1_node;
static ul_treeNodeType route_0x28L_apps_proc_usb_hs_node;
static ul_treeNodeType route_0x29L_apps_proc_pdm_node;
static ul_treeNodeType route_0x2cL_apps_proc_prng_node;
static ul_treeNodeType route_0x32L_apps_proc_tcsr_node;
static ul_treeNodeType route_0x33L_apps_proc_tlmm_node;
static ul_treeNodeType route_0x36L_apps_proc_imem_cfg_node;
static ul_treeNodeType route_0x37L_apps_proc_message_ram_node;
static ul_treeNodeType route_0x3bL_apps_proc_pmic_arb_node;
static ul_treeNodeType route_0x3fL_apps_proc_qdss_cfg_node;
static ul_treeNodeType route_0x5fL_apps_proc_usb_phy_node;
static ul_treeNodeType route_0x69L_apps_proc_audio_node;
static ul_treeNodeType route_0x1300000000L_qdss_bam_ebi_node;
static ul_treeNodeType route_0x130000001aL_qdss_bam_imem_node;
static ul_treeNodeType route_0x1300000028L_qdss_bam_usb_hs_node;
static ul_treeNodeType route_0x1700000000L_crypto_c0_ebi_node;
static ul_treeNodeType route_0x170000001aL_crypto_c0_imem_node;
static ul_treeNodeType route_0x1f00000000L_qdss_etr_ebi_node;
static ul_treeNodeType route_0x1f0000001aL_qdss_etr_imem_node;
static ul_treeNodeType route_0x1f00000028L_qdss_etr_usb_hs_node;
static ul_treeNodeType route_0x2900000000L_blsp_1_ebi_node;
static ul_treeNodeType route_0x290000001aL_blsp_1_imem_node;
static ul_treeNodeType route_0x290000001eL_blsp_1_qdss_stm_node;
static ul_treeNodeType route_0x3a00000000L_qpic_ebi_node;
static ul_treeNodeType route_0x3a0000001aL_qpic_imem_node;
static ul_treeNodeType route_0x3a0000001eL_qpic_qdss_stm_node;
static ul_treeNodeType route_0x4e00000000L_audio_ebi_node;
static ul_treeNodeType route_0x4e0000001aL_audio_imem_node;
static ul_treeNodeType route_0x4e0000001eL_audio_qdss_stm_node;
static ul_treeNodeType route_0x8900000000L_usb_hs1_ebi_node;
static ul_treeNodeType route_0x890000001aL_usb_hs1_imem_node;
static ul_treeNodeType route_0x890000001eL_usb_hs1_qdss_stm_node;
static ul_treeNodeType route_0x890000003fL_usb_hs1_qdss_cfg_node;

/* Create the tree */
static ul_treeNodeType route_0x0L_apps_proc_ebi_node =
{
  0x0ULL,                                 /* KEY: MASTER_ID:SLAVE_ID */
  &route_apps_proc_ebi_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1aL_apps_proc_imem_node =
{
  0x1aULL,                                /* KEY: MASTER_ID:SLAVE_ID */
  &route_apps_proc_imem_list,
  &route_0x0L_apps_proc_ebi_node,
  &route_0x1eL_apps_proc_qdss_stm_node
};
static ul_treeNodeType route_0x1eL_apps_proc_qdss_stm_node =
{
  0x1eULL,                                /* KEY: MASTER_ID:SLAVE_ID */
  &route_apps_proc_qdss_stm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x27L_apps_proc_blsp_1_node =
{
  0x27ULL,                                /* KEY: MASTER_ID:SLAVE_ID */
  &route_apps_proc_blsp_1_list,
  &route_0x1aL_apps_proc_imem_node,
  &route_0x2cL_apps_proc_prng_node
};
static ul_treeNodeType route_0x28L_apps_proc_usb_hs_node =
{
  0x28ULL,                                /* KEY: MASTER_ID:SLAVE_ID */
  &route_apps_proc_usb_hs_list,
  NULL,
  &route_0x29L_apps_proc_pdm_node
};
static ul_treeNodeType route_0x29L_apps_proc_pdm_node =
{
  0x29ULL,                                /* KEY: MASTER_ID:SLAVE_ID */
  &route_apps_proc_pdm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x2cL_apps_proc_prng_node =
{
  0x2cULL,                                /* KEY: MASTER_ID:SLAVE_ID */
  &route_apps_proc_prng_list,
  &route_0x28L_apps_proc_usb_hs_node,
  &route_0x32L_apps_proc_tcsr_node
};
static ul_treeNodeType route_0x32L_apps_proc_tcsr_node =
{
  0x32ULL,                                /* KEY: MASTER_ID:SLAVE_ID */
  &route_apps_proc_tcsr_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x33L_apps_proc_tlmm_node =
{
  0x33ULL,                                /* KEY: MASTER_ID:SLAVE_ID */
  &route_apps_proc_tlmm_list,
  &route_0x27L_apps_proc_blsp_1_node,
  &route_0x3fL_apps_proc_qdss_cfg_node
};
static ul_treeNodeType route_0x36L_apps_proc_imem_cfg_node =
{
  0x36ULL,                                /* KEY: MASTER_ID:SLAVE_ID */
  &route_apps_proc_imem_cfg_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x37L_apps_proc_message_ram_node =
{
  0x37ULL,                                /* KEY: MASTER_ID:SLAVE_ID */
  &route_apps_proc_message_ram_list,
  &route_0x36L_apps_proc_imem_cfg_node,
  &route_0x3bL_apps_proc_pmic_arb_node
};
static ul_treeNodeType route_0x3bL_apps_proc_pmic_arb_node =
{
  0x3bULL,                                /* KEY: MASTER_ID:SLAVE_ID */
  &route_apps_proc_pmic_arb_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x3fL_apps_proc_qdss_cfg_node =
{
  0x3fULL,                                /* KEY: MASTER_ID:SLAVE_ID */
  &route_apps_proc_qdss_cfg_list,
  &route_0x37L_apps_proc_message_ram_node,
  &route_0x5fL_apps_proc_usb_phy_node
};
static ul_treeNodeType route_0x5fL_apps_proc_usb_phy_node =
{
  0x5fULL,                                /* KEY: MASTER_ID:SLAVE_ID */
  &route_apps_proc_usb_phy_list,
  NULL,
  &route_0x69L_apps_proc_audio_node
};
static ul_treeNodeType route_0x69L_apps_proc_audio_node =
{
  0x69ULL,                                /* KEY: MASTER_ID:SLAVE_ID */
  &route_apps_proc_audio_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1300000000L_qdss_bam_ebi_node =
{
  0x1300000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qdss_bam_ebi_list,
  &route_0x33L_apps_proc_tlmm_node,
  &route_0x2900000000L_blsp_1_ebi_node
};
static ul_treeNodeType route_0x130000001aL_qdss_bam_imem_node =
{
  0x130000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qdss_bam_imem_list,
  NULL,
  &route_0x1300000028L_qdss_bam_usb_hs_node
};
static ul_treeNodeType route_0x1300000028L_qdss_bam_usb_hs_node =
{
  0x1300000028ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qdss_bam_usb_hs_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1700000000L_crypto_c0_ebi_node =
{
  0x1700000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_crypto_c0_ebi_list,
  &route_0x130000001aL_qdss_bam_imem_node,
  &route_0x170000001aL_crypto_c0_imem_node
};
static ul_treeNodeType route_0x170000001aL_crypto_c0_imem_node =
{
  0x170000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_crypto_c0_imem_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1f00000000L_qdss_etr_ebi_node =
{
  0x1f00000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qdss_etr_ebi_list,
  &route_0x1700000000L_crypto_c0_ebi_node,
  &route_0x1f00000028L_qdss_etr_usb_hs_node
};
static ul_treeNodeType route_0x1f0000001aL_qdss_etr_imem_node =
{
  0x1f0000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qdss_etr_imem_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1f00000028L_qdss_etr_usb_hs_node =
{
  0x1f00000028ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qdss_etr_usb_hs_list,
  &route_0x1f0000001aL_qdss_etr_imem_node,
  NULL
};
static ul_treeNodeType route_0x2900000000L_blsp_1_ebi_node =
{
  0x2900000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_1_ebi_list,
  &route_0x1f00000000L_qdss_etr_ebi_node,
  &route_0x4e00000000L_audio_ebi_node
};
static ul_treeNodeType route_0x290000001aL_blsp_1_imem_node =
{
  0x290000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_1_imem_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x290000001eL_blsp_1_qdss_stm_node =
{
  0x290000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_1_qdss_stm_list,
  &route_0x290000001aL_blsp_1_imem_node,
  &route_0x3a00000000L_qpic_ebi_node
};
static ul_treeNodeType route_0x3a00000000L_qpic_ebi_node =
{
  0x3a00000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qpic_ebi_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x3a0000001aL_qpic_imem_node =
{
  0x3a0000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qpic_imem_list,
  &route_0x290000001eL_blsp_1_qdss_stm_node,
  &route_0x3a0000001eL_qpic_qdss_stm_node
};
static ul_treeNodeType route_0x3a0000001eL_qpic_qdss_stm_node =
{
  0x3a0000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qpic_qdss_stm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x4e00000000L_audio_ebi_node =
{
  0x4e00000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_audio_ebi_list,
  &route_0x3a0000001aL_qpic_imem_node,
  &route_0x8900000000L_usb_hs1_ebi_node
};
static ul_treeNodeType route_0x4e0000001aL_audio_imem_node =
{
  0x4e0000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_audio_imem_list,
  NULL,
  &route_0x4e0000001eL_audio_qdss_stm_node
};
static ul_treeNodeType route_0x4e0000001eL_audio_qdss_stm_node =
{
  0x4e0000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_audio_qdss_stm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x8900000000L_usb_hs1_ebi_node =
{
  0x8900000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_usb_hs1_ebi_list,
  &route_0x4e0000001aL_audio_imem_node,
  &route_0x890000001eL_usb_hs1_qdss_stm_node
};
static ul_treeNodeType route_0x890000001aL_usb_hs1_imem_node =
{
  0x890000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_usb_hs1_imem_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x890000001eL_usb_hs1_qdss_stm_node =
{
  0x890000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_usb_hs1_qdss_stm_list,
  &route_0x890000001aL_usb_hs1_imem_node,
  &route_0x890000003fL_usb_hs1_qdss_cfg_node
};
static ul_treeNodeType route_0x890000003fL_usb_hs1_qdss_cfg_node =
{
  0x890000003fULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_usb_hs1_qdss_cfg_list,
  NULL,
  NULL
};

/*============================================================================
                   EXTERNAL DATA DECLARATIONS
============================================================================*/
/* Pointer to the root node */
ul_treeNodeType * route_tree_root = 
  &route_0x1300000000L_qdss_bam_ebi_node;

const uint32 u32ul_arb_master_list_size   = 16;
ul_master_data_type *ul_arb_master_list[] =
{
  &master_apps_proc,
  &master_audio,
  &master_bimc_pcnoc,
  &master_blsp_1,
  &master_cr_virt_pcnoc,
  &master_crypto_c0,
  &master_pcnoc_bimc_1,
  &master_pcnoc_int_0,
  &master_pcnoc_int_1,
  &master_pcnoc_int_2,
  &master_pcnoc_int_3,
  &master_pcnoc_m_0,
  &master_qdss_bam,
  &master_qdss_etr,
  &master_qpic,
  &master_usb_hs1,
};

const uint32 u32ul_arb_slave_list_size   = 23;
ul_slave_data_type *ul_arb_slave_list[] =
{
  &slave_audio,
  &slave_bimc_pcnoc,
  &slave_blsp_1,
  &slave_cr_virt_pcnoc,
  &slave_ebi,
  &slave_imem,
  &slave_imem_cfg,
  &slave_message_ram,
  &slave_pcnoc_bimc_1,
  &slave_pcnoc_int_0,
  &slave_pcnoc_int_1,
  &slave_pcnoc_int_2,
  &slave_pcnoc_int_3,
  &slave_pcnoc_m_0,
  &slave_pdm,
  &slave_pmic_arb,
  &slave_prng,
  &slave_qdss_cfg,
  &slave_qdss_stm,
  &slave_tcsr,
  &slave_tlmm,
  &slave_usb_hs,
  &slave_usb_phy,
};

/* Have to make the array size a const so we can export it */
const uint32 u32ul_arb_clk_node_list_size   = 2;
const char *ul_arb_clock_node_list[] =
{
  "/clk/bimc",
  "/clk/pcnoc",
};

