#===============================================================================
#
# Secure Camera Library
#
# GENERAL DESCRIPTION
#    build script
#
# Copyright (c) 2016-2017 by Qualcomm Technologies, Inc. All Rights Reserved.
# Qualcomm Technologies Proprietary and Confidential.
#
#-------------------------------------------------------------------------------
#
#  $Header: //components/rel/apps.tz/2.1.3/securemsm/trustzone/qsapps/seccamlib/src/SConscript#1 $
#  $DateTime: 2019/05/23 05:23:25 $
#  $Author: pwbldsvc $
#  $Change: 19291951 $
#                      EDIT HISTORY FOR FILE
#
#  This section contains schedulerents describing changes made to the module.
#  Notice that changes are listed in reverse chronological order.
#
# when       who     what, where, why
# --------   ---     ---------------------------------------------------------
# 08/14/17    dr     Port to sdm845
# 01/01/17    dr     Created
#===============================================================================
Import('env')
env = env.Clone()


libname = 'seccam_lib'

includes = [
   "../inc",
   '${BUILD_ROOT}/apps/securemsm/trustzone/qsapps/misc_headers',
]

sources = ['seccamlib.c',]

lib = env.SecureAppLibBuilder(
    includes = includes,
    sources = sources,
    libname = libname,
    deploy_sources = ['SConscript',
                       env.Glob('../inc/*.h'),
                     ],
    deploy_lib = True,
    deploy_variants = env.GetDefaultPublicVariants()
    )
Return('lib')
