/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Fri Jul 14 02:01:36 2017. */

#ifndef PB_SNS_AMD_PB_H_INCLUDED
#define PB_SNS_AMD_PB_H_INCLUDED
#include <pb.h>

#include "sns_std_sensor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _sns_amd_msgid {
    SNS_AMD_MSGID_SNS_AMD_EVENT = 772
} sns_amd_msgid;
#define _sns_amd_msgid_MIN SNS_AMD_MSGID_SNS_AMD_EVENT
#define _sns_amd_msgid_MAX SNS_AMD_MSGID_SNS_AMD_EVENT
#define _sns_amd_msgid_ARRAYSIZE ((sns_amd_msgid)(SNS_AMD_MSGID_SNS_AMD_EVENT+1))
#define sns_amd_msgid_SNS_AMD_MSGID_SNS_AMD_EVENT SNS_AMD_MSGID_SNS_AMD_EVENT

typedef enum _sns_amd_event_type {
    SNS_AMD_EVENT_TYPE_UNKNOWN = 0,
    SNS_AMD_EVENT_TYPE_STATIONARY = 1,
    SNS_AMD_EVENT_TYPE_MOTION = 2
} sns_amd_event_type;
#define _sns_amd_event_type_MIN SNS_AMD_EVENT_TYPE_UNKNOWN
#define _sns_amd_event_type_MAX SNS_AMD_EVENT_TYPE_MOTION
#define _sns_amd_event_type_ARRAYSIZE ((sns_amd_event_type)(SNS_AMD_EVENT_TYPE_MOTION+1))
#define sns_amd_event_type_SNS_AMD_EVENT_TYPE_UNKNOWN SNS_AMD_EVENT_TYPE_UNKNOWN
#define sns_amd_event_type_SNS_AMD_EVENT_TYPE_STATIONARY SNS_AMD_EVENT_TYPE_STATIONARY
#define sns_amd_event_type_SNS_AMD_EVENT_TYPE_MOTION SNS_AMD_EVENT_TYPE_MOTION

/* Struct definitions */
typedef struct _sns_amd_event {
    sns_amd_event_type state;
/* @@protoc_insertion_point(struct:sns_amd_event) */
} sns_amd_event;

/* Default values for struct fields */
extern const sns_amd_event_type sns_amd_event_state_default;

/* Initializer values for message structs */
#define sns_amd_event_init_default               {SNS_AMD_EVENT_TYPE_UNKNOWN}
#define sns_amd_event_init_zero                  {(sns_amd_event_type)0}

/* Field tags (for use in manual encoding/decoding) */
#define sns_amd_event_state_tag                  1

/* Struct field encoding specification for nanopb */
extern const pb_field_t sns_amd_event_fields[2];

/* Maximum encoded size of messages (where known) */
#define sns_amd_event_size                       2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SNS_AMD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
