/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Fri Jul 14 02:01:38 2017. */

#ifndef PB_SNS_MOTION_DETECT_PB_H_INCLUDED
#define PB_SNS_MOTION_DETECT_PB_H_INCLUDED
#include <pb.h>

#include "sns_std_sensor.pb.h"

#include "sns_physical_sensor_test.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _sns_motion_detect_msgid {
    SNS_MOTION_DETECT_MSGID_SNS_MOTION_DETECT_EVENT = 771
} sns_motion_detect_msgid;
#define _sns_motion_detect_msgid_MIN SNS_MOTION_DETECT_MSGID_SNS_MOTION_DETECT_EVENT
#define _sns_motion_detect_msgid_MAX SNS_MOTION_DETECT_MSGID_SNS_MOTION_DETECT_EVENT
#define _sns_motion_detect_msgid_ARRAYSIZE ((sns_motion_detect_msgid)(SNS_MOTION_DETECT_MSGID_SNS_MOTION_DETECT_EVENT+1))
#define sns_motion_detect_msgid_SNS_MOTION_DETECT_MSGID_SNS_MOTION_DETECT_EVENT SNS_MOTION_DETECT_MSGID_SNS_MOTION_DETECT_EVENT

typedef enum _sns_motion_detect_event_type {
    SNS_MOTION_DETECT_EVENT_TYPE_DISABLED = 0,
    SNS_MOTION_DETECT_EVENT_TYPE_ENABLED = 1,
    SNS_MOTION_DETECT_EVENT_TYPE_FIRED = 2
} sns_motion_detect_event_type;
#define _sns_motion_detect_event_type_MIN SNS_MOTION_DETECT_EVENT_TYPE_DISABLED
#define _sns_motion_detect_event_type_MAX SNS_MOTION_DETECT_EVENT_TYPE_FIRED
#define _sns_motion_detect_event_type_ARRAYSIZE ((sns_motion_detect_event_type)(SNS_MOTION_DETECT_EVENT_TYPE_FIRED+1))
#define sns_motion_detect_event_type_SNS_MOTION_DETECT_EVENT_TYPE_DISABLED SNS_MOTION_DETECT_EVENT_TYPE_DISABLED
#define sns_motion_detect_event_type_SNS_MOTION_DETECT_EVENT_TYPE_ENABLED SNS_MOTION_DETECT_EVENT_TYPE_ENABLED
#define sns_motion_detect_event_type_SNS_MOTION_DETECT_EVENT_TYPE_FIRED SNS_MOTION_DETECT_EVENT_TYPE_FIRED

/* Struct definitions */
typedef struct _sns_motion_detect_event {
    sns_motion_detect_event_type motion_detect_event_type;
/* @@protoc_insertion_point(struct:sns_motion_detect_event) */
} sns_motion_detect_event;

/* Default values for struct fields */
extern const sns_motion_detect_event_type sns_motion_detect_event_motion_detect_event_type_default;

/* Initializer values for message structs */
#define sns_motion_detect_event_init_default     {SNS_MOTION_DETECT_EVENT_TYPE_DISABLED}
#define sns_motion_detect_event_init_zero        {(sns_motion_detect_event_type)0}

/* Field tags (for use in manual encoding/decoding) */
#define sns_motion_detect_event_motion_detect_event_type_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t sns_motion_detect_event_fields[2];

/* Maximum encoded size of messages (where known) */
#define sns_motion_detect_event_size             2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SNS_MOTION_DETECT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
