/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Fri Jul 14 02:01:39 2017. */

#ifndef PB_SNS_PRESSURE_PB_H_INCLUDED
#define PB_SNS_PRESSURE_PB_H_INCLUDED
#include <pb.h>

#include "sns_std_sensor.pb.h"

#include "sns_physical_sensor_test.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
