/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Thu Jul 27 02:11:26 2017. */

#ifndef PB_SNS_GYRO_CAL_PB_H_INCLUDED
#define PB_SNS_GYRO_CAL_PB_H_INCLUDED
#include <pb.h>

#include "sns_cal.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
