/*!
  @file lte_rrc_dt_ul_data_rlf_failure_test.cpp

  @brief
  Unit test code for RRC DT state transitions.
  1. Check if DT is in READY state
  2. Send CRE Started Indication
  3. Check if DT is in BLOCKED state
  4. Send UL data req
  5. Send UL data req
  6. Send Connection Release Indication
  7. Check if internal table is empty
  8. Check if DT is in READY state

*/

/*===========================================================================

  Copyright (c) 2008 Qualcomm Technologies Incorporated. All Rights Reserved

  Qualcomm Proprietary

  Export of this technology or software is regulated by the U.S. Government.
  Diversion contrary to U.S. law prohibited.

  All ideas, data and information contained in or disclosed by
  this document are confidential and proprietary information of
  Qualcomm Technologies Incorporated and all rights therein are expressly reserved.
  By accepting this material the recipient agrees that this material
  and the information contained therein are held in confidence and in
  trust and will not be used, copied, reproduced in whole or in part,
  nor its contents revealed in any manner to others without the express
  written permission of Qualcomm Technologies Incorporated.

===========================================================================*/

/*===========================================================================

EDIT HISTORY FOR MODULE

This section contains comments describing changes made to the module.
Notice that changes are listed in reverse chronological order.

$Header: 

when       who     what, where, why
--------   ---     ----------------------------------------------------------
02/03/09   vatsac  Initial Revision
           
===========================================================================*/

/*===========================================================================

INCLUDE FILES

===========================================================================*/
extern "C"
{
#include <lte_rrc_int_msg.h>
#include <lte_rrc_dti.h>
#include <lte_rrc_utils.h>
#include <dsm_item.h>
#include <dsm_init.h>
  
}

#include <TestFramework.h>
#include <lte_rrc_utf.h>

#include "lte_rrc_dt_test_common.h"

//external messages generated by code under test
static uint32 ext_umid_list[] = 
{ 
    LTE_RRC_UL_DATA_CNF
};

//message structures
static lte_rrc_cre_started_indi_s           cre_started_indi;
static lte_rrc_ul_data_req_s                ul_data_req;
static lte_rrc_irat_tunnel_ul_msg_req_s     tunnel_ul_msg_req;
static lte_rrc_conn_released_indi_s         conn_release_ind;
static lte_rrc_nas_msg_container_s          nas_msg_container;

extern "C"
{
    extern lte_rrc_dt_data_s lte_rrc_dt_data;
}

/*===========================================================================

UNIT TEST

===========================================================================*/

TF_DEFINE_TEST_CASE(COMPONENT, LteRrcDtULDataRlfFailureTest);

void LteRrcDtULDataRlfFailureTest::Setup()
{
    lte_rrc_utf_setup(LTE_RRC_DT_SM, ext_umid_list, 1);
    lte_rrc_test_dt_init();
}

void LteRrcDtULDataRlfFailureTest::Test()
{
    dsm_item_type *dsm_ptr=NULL;
    /* Message attachment pointer */
    msgr_attach_struct_type *att_ptr;
  
    TF_MSG("Start of test");

    lte_rrc_test_dt_set_controller_state(LTE_RRC_CONTROLLER_SM__CONNECTED);

    TF_MSG("Checking for READY state");
    TF_ASSERT(stm_get_state(LTE_RRC_DT_SM) == LTE_RRC_DT_SM__READY);

    TF_MSG("Sending CRE Started Indication");
    lte_rrc_init_default_hdr(&cre_started_indi.msg_hdr, LTE_RRC_HANDOVER_STARTED_INDI);
    lte_rrc_utf_send_msg((byte*)&cre_started_indi, sizeof(cre_started_indi));

    lte_rrc_utf_wait_for_done();

    TF_MSG("Checking for BLOCKED state");
    TF_ASSERT(stm_get_state(LTE_RRC_DT_SM) == LTE_RRC_DT_SM__BLOCKED);

    TF_MSG("Sending First UL Information Transfer Message");
    msgr_init_hdr_attach(&ul_data_req.msg_hdr, MSGR_LTE_RRC, LTE_RRC_UL_DATA_REQ, 0, 1);
    
    ul_data_req.trans_id = 1;
    // ul_data_req.priority;
    ul_data_req.cnf_is_reqd = true;
    nas_msg_container.msg_size = LTE_RRC_MAX_NAS_MSG_CONTAINER_SIZE;
    memset(nas_msg_container.msg_payload, 'A',
           nas_msg_container.msg_size);

    /* Pushdown DSM */
    LTE_ASSERT(dsm_pushdown(&dsm_ptr, nas_msg_container.msg_payload, 
														(uint16)LTE_RRC_MAX_NAS_MSG_CONTAINER_SIZE, 
														LTE_RRC_DSM_POOL((uint16)LTE_RRC_MAX_NAS_MSG_CONTAINER_SIZE)) 
        == (uint16)LTE_RRC_MAX_NAS_MSG_CONTAINER_SIZE);

    /* Set DSM attach */
    att_ptr = msgr_get_attach(&ul_data_req.msg_hdr, 0);
    LTE_ASSERT(att_ptr != NULL);
    msgr_set_dsm_attach(att_ptr, dsm_ptr);
    
    LTE_ASSERT(dsm_ptr != NULL);
    
    lte_rrc_utf_send_msg((byte*)&ul_data_req, sizeof(ul_data_req));

    lte_rrc_utf_wait_for_done();

    TF_MSG("Sending Second UL Information Transfer Message");
    msgr_init_hdr_attach(&ul_data_req.msg_hdr, MSGR_LTE_RRC, LTE_RRC_UL_DATA_REQ, 0, 1);
    
    ul_data_req.trans_id = 2;
    // ul_data_req.priority;
    ul_data_req.cnf_is_reqd = true;
    nas_msg_container.msg_size = LTE_RRC_MAX_NAS_MSG_CONTAINER_SIZE;
    memset(nas_msg_container.msg_payload, 'A',
           nas_msg_container.msg_size);
    
    dsm_ptr = NULL;
    /* Pushdown DSM */
    LTE_ASSERT(dsm_pushdown(&dsm_ptr, nas_msg_container.msg_payload, 
														(uint16)LTE_RRC_MAX_NAS_MSG_CONTAINER_SIZE, 
														LTE_RRC_DSM_POOL((uint16)LTE_RRC_MAX_NAS_MSG_CONTAINER_SIZE)) 
        == (uint16)LTE_RRC_MAX_NAS_MSG_CONTAINER_SIZE);

    /* Set DSM attach */
    att_ptr = msgr_get_attach(&ul_data_req.msg_hdr, 0);
    LTE_ASSERT(att_ptr != NULL);
    msgr_set_dsm_attach(att_ptr, dsm_ptr);
    
    LTE_ASSERT(dsm_ptr != NULL);
    
    lte_rrc_utf_send_msg((byte*)&ul_data_req, sizeof(ul_data_req));

    lte_rrc_utf_wait_for_done();

    TF_MSG("Sending First IRAT Tunnel UL Information Transfer Message to DT ");
    lte_rrc_init_default_hdr(&tunnel_ul_msg_req.msg_hdr, LTE_RRC_IRAT_TUNNEL_UL_MSG_REQ);

    tunnel_ul_msg_req.cnf_is_reqd = true;
    tunnel_ul_msg_req.trans_id = 7;
    tunnel_ul_msg_req.msg.ul_msg_type = LTE_IRAT_TUNNEL_UL_MSG_INFO_TRANSFER_REQ;
    tunnel_ul_msg_req.msg.ul_msg_u.ul_info_tx.type = LTE_IRAT_RAT_TYPE_1XRTT;
    tunnel_ul_msg_req.msg.ul_msg_u.ul_info_tx.msg_container.msg_size = LTE_RRC_MAX_NAS_MSG_CONTAINER_SIZE;

    memset(tunnel_ul_msg_req.msg.ul_msg_u.ul_info_tx.msg_container.msg_payload, 'A',
           tunnel_ul_msg_req.msg.ul_msg_u.ul_info_tx.msg_container.msg_size);
    lte_rrc_utf_send_msg((byte*)&tunnel_ul_msg_req, sizeof(tunnel_ul_msg_req));

    lte_rrc_utf_wait_for_done();

    TF_MSG("Sending Second IRAT Tunnel UL Information Transfer Message to DT ");
    lte_rrc_init_default_hdr(&tunnel_ul_msg_req.msg_hdr, LTE_RRC_IRAT_TUNNEL_UL_MSG_REQ);

    tunnel_ul_msg_req.cnf_is_reqd = true;
    tunnel_ul_msg_req.trans_id = 9;
    tunnel_ul_msg_req.msg.ul_msg_type = LTE_IRAT_TUNNEL_UL_MSG_INFO_TRANSFER_REQ;
    tunnel_ul_msg_req.msg.ul_msg_u.ul_info_tx.type = LTE_IRAT_RAT_TYPE_1XRTT;
    tunnel_ul_msg_req.msg.ul_msg_u.ul_info_tx.msg_container.msg_size = LTE_RRC_MAX_NAS_MSG_CONTAINER_SIZE;

    memset(tunnel_ul_msg_req.msg.ul_msg_u.ul_info_tx.msg_container.msg_payload, 'B',
           tunnel_ul_msg_req.msg.ul_msg_u.ul_info_tx.msg_container.msg_size);
    lte_rrc_utf_send_msg((byte*)&tunnel_ul_msg_req, sizeof(tunnel_ul_msg_req));

    lte_rrc_utf_wait_for_done();
    
    TF_MSG("Sending Connection Release Indication");
    lte_rrc_init_default_hdr(&conn_release_ind.msg_hdr, LTE_RRC_CONN_RELEASED_INDI);
    lte_rrc_utf_send_msg((byte*)&conn_release_ind, sizeof(conn_release_ind));

    lte_rrc_utf_wait_for_done();

    /* check internal table */ 
    for (int i = 0; i < LTE_RRC_DT_MAX_UL_DATA_RECORDS; i++)
    {
        TF_ASSERT(lte_rrc_dt_data.d_ptr->lte_rrc_dt_ul_data_table[i].record_is_valid == FALSE);
        //TF_ASSERT(lte_rrc_dt_data.d_ptr->lte_rrc_dt_irat_ul_data_table[i].record_is_valid == FALSE);
    }

    TF_MSG("Checking for READY state");
    TF_ASSERT(stm_get_state(LTE_RRC_DT_SM) == LTE_RRC_DT_SM__READY);

    TF_MSG("End of test");
}

void LteRrcDtULDataRlfFailureTest::Teardown()
{
    lte_rrc_utf_teardown();
    lte_rrc_test_dt_teardown();
}

