/*
 * Copyright (c) 2020-2021 Qualcomm Technologies, Inc.
 * All Rights Reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 */

/**
* @addtogroup CDeviceAttestation
* @{
  Class CDeviceAttestation implements \link IDeviceAttestation \endlink interface.

  The class ID `CDeviceAttestation` is not included in the default privilege set. It needs to be added to the
  privileges section in the metadata to allow the TA to use the CDeviceAttestation class.
*/

const uint32 CDeviceAttestation_UID = 62;

/** @} */