/*!
  @file lte_rrc_llc_invalid_conn_setup_no_ul_specific_param_test.cpp

  @brief
  Unit test code for the LLC procedure that tests the processing of 
  a Connection Setup message.

*/

/*===========================================================================

  Copyright (c) 2008 Qualcomm Technologies Incorporated. All Rights Reserved

  Qualcomm Proprietary

  Export of this technology or software is regulated by the U.S. Government.
  Diversion contrary to U.S. law prohibited.

  All ideas, data and information contained in or disclosed by
  this document are confidential and proprietary information of
  Qualcomm Technologies Incorporated and all rights therein are expressly reserved.
  By accepting this material the recipient agrees that this material
  and the information contained therein are held in confidence and in
  trust and will not be used, copied, reproduced in whole or in part,
  nor its contents revealed in any manner to others without the express
  written permission of Qualcomm Technologies Incorporated.

===========================================================================*/

/*===========================================================================

                        EDIT HISTORY FOR MODULE

This section contains comments describing changes made to the module.
Notice that changes are listed in reverse chronological order.

$Header:

when       who     what, where, why
--------   ---     ----------------------------------------------------------
05/08/09   da     Initial Revision
           
===========================================================================*/

/*===========================================================================

                           INCLUDE FILES

===========================================================================*/
extern "C"
{
#include "__lte_rrc_llc.h"
#include "lte_static_rrc_mem_util.h"

}

#include "TestFramework.h"
#include "lte_rrc_utf.h"
#include "lte_rrc_llc_test_common.h"

/*===========================================================================

                         INTERNAL VARIABLES

===========================================================================*/

//external messages generated by code under test
static uint32 ext_umid_list[] = 
{ 
  LTE_CPHY_DEDICATED_CFG_REQ,
};

/*===========================================================================

                                UNIT TEST

===========================================================================*/

TF_DEFINE_TEST_CASE(COMPONENT, LteRrcLlcInvalidConnSetupNoUlSpecificParamTest);

void LteRrcLlcInvalidConnSetupNoUlSpecificParamTest::Setup()
{
  lte_rrc_utf_setup(LTE_RRC_LLC_SM, ext_umid_list, 1);
  lte_rrc_llc_test_stub_init();
}

void LteRrcLlcInvalidConnSetupNoUlSpecificParamTest::Test()
{
  lte_rrc_pdu_buf_s encoded_pdu;
  lte_rrc_osys_DL_CCCH_Message *ccch_msg_ptr;
  int decode_status = 0;
  /* ---------------------------------------------------------------------- */
  TF_MSG("\nInvalid Connection Setup with no UL specific param test Begins \n");

  encoded_pdu.length = sizeof(llc_conn_setup_msg);
  encoded_pdu.value = llc_conn_setup_msg;

  /* On receiving a Config Req from CEP, LLC should be in the INITIAL state */
  TF_ASSERT(lte_rrc_llc_get_state() == LTE_RRC_LLC_SM__INITIAL);

  /* Construct asn1 pdu to be sent to the Config module after decoding the 
     encoded pdu*/
  ccch_msg_ptr = (lte_rrc_osys_DL_CCCH_Message *)lte_rrc_osys_asn1_decode_pdu(encoded_pdu.value, encoded_pdu.length, 
                               DL_CCCH_Message, &decode_status);
  TF_ASSERT(decode_status == 0);

  /* Modify message so that SRB add\modify list is not present */
  TF_ASSERT(ccch_msg_ptr != NULL);
  ccch_msg_ptr->message.u.c1->u.rrcConnectionSetup->criticalExtensions.u.c1->u.
    rrcConnectionSetup_r8->radioResourceConfigDedicated.srb_ToAddModList.elem->logicalChannelConfig.
    u.explicitValue->m.ul_SpecificParametersPresent = 0;
  lte_rrc_llc_test_common_data.dl_ccch_msg_ptr = ccch_msg_ptr;

  /* Send LTE_RRC_CFG_REQI to LLC */
  lte_rrc_llc_test_construct_and_send_ded_cfg_reqi(&encoded_pdu, LTE_RRC_PROC_CEP, TRUE);
  /* Verify CFG_CNFI from LLC */
  lte_rrc_llc_test_verify_cfg_cnfi(E_DATA_INVALID, LTE_RRC_PROC_CEP, NULL);

  TF_MSG("\nInvalid Connection Setup no UL specific param Ends \n");
  lte_rrc_llc_test_free_dl_ded_msg_ptr();
  lte_rrc_utf_reset(); 

  /* ---------------------------------------------------------------------- */
}

void LteRrcLlcInvalidConnSetupNoUlSpecificParamTest::Teardown()
{
  lte_rrc_utf_teardown();
}



